import { oc2Theme } from "@opencode-ai/ui/theme/default-themes"
import { resolveThemeVariant } from "@opencode-ai/ui/theme/resolve"
import { COLOR_LITERAL, contrast, extreme, formatColor, fromLch, over, parseColor, toLch, type Rgba } from "./color"
import type { PaletteRoles } from "./convert"
import { colorTokens, hasColor, paletteRules, parseCss, type CssNode, type Declaration } from "./css"
import type { PaletteDefinition } from "./definitions"
import { colors, surfaces, tokenTable } from "./measure"
import { createRemap, remapValue, type Anchors } from "./remap"

// Orchestra's own stylesheets under packages/app/src, in the order the app loads them.
export const PALETTE_SOURCES = [
  "orchestra/background.css",
  "orchestra/theme.css",
  "orchestra/shell.css",
  "orchestra/tabs.css",
  "orchestra/session.css",
  "orchestra/composer.css",
  "orchestra/review.css",
  "orchestra/evidence.css",
  "orchestra/chapters/kit.css",
  "orchestra/chapters/kpis.css",
  "orchestra/chapters/agents.css",
  "orchestra/chapters/cicd.css",
  "orchestra/chapters/dock.css",
  "orchestra/chapters/env.css",
  "orchestra/chapters/mcp.css",
  "orchestra/chapters/plugins.css",
  "orchestra/chapters/providers.css",
  "orchestra/chapters/schedule.css",
  "orchestra/chapters/shortcuts.css",
  "orchestra/chapters/skills.css",
  "orchestra/chapters/workspaces.css",
  "components/settings-v2/view/settings-view.css",
  "pages/session/apps-panel.css",
  "pages/session/orchestra-cockpit.css",
  "pages/session/orchestra-dock.css",
  "pages/session/orchestra-governance.css",
  "pages/session/linux-menu.css",
]

// Text in these files sits on the session's glass; everything else sits on the panel glass.
const SESSION_SOURCES = new Set([
  "orchestra/session.css",
  "orchestra/composer.css",
  "orchestra/review.css",
  "orchestra/evidence.css",
  "pages/session/apps-panel.css",
  "pages/session/orchestra-cockpit.css",
  "pages/session/orchestra-dock.css",
  "pages/session/orchestra-governance.css",
])

// Role tokens every palette holds at AA even where no Orchestra stylesheet sets them as `color`.
const ROLE_TOKENS = new Set([
  "--orchestra-text",
  "--orchestra-body",
  "--orchestra-muted",
  "--orchestra-accent",
  "--orchestra-success",
  "--orchestra-warm",
  "--orchestra-danger",
  "--mx-strong",
  "--mx-dim",
  "--mx-blue",
  "--mx-good",
  "--mx-bad",
])

export const AA = 4.5
const CODE_SOURCE = "code"

export type Source = { path: string; nodes: CssNode[] }
export type TextCheck = { source: string; name: string; value: string; ratio: number }

export function parseSources(texts: Record<string, string>): Source[] {
  // A Windows checkout reads the stylesheets with CRLF; the output must not depend on the checkout.
  return PALETTE_SOURCES.map((path) => ({ path, nodes: parseCss((texts[path] ?? "").replaceAll("\r\n", "\n")) }))
}

const HEADER = "/* Generated by packages/app/script/orchestra-palettes.ts from Orchestra's stylesheets. Do not edit. */"

/** Every generated palette file by name, and the text colors that kept a palette from shipping. */
export function generatePalettes(sources: Source[], definitions: PaletteDefinition[]) {
  const built = definitions.map((definition) => ({ definition, ...buildPalette(definition, sources) }))
  const base = (["dark", "light"] as const).map((scheme) =>
    swatch(
      scheme,
      tokenTable(
        sources.map((source) => source.nodes),
        scheme,
      ),
    ),
  )
  return {
    files: {
      "first-paint.css": [HEADER, ...built.map((item) => item.firstPaint)].join("\n") + "\n",
      "swatches.css": [HEADER, ...base, ...built.map((item) => item.swatch)].join("\n") + "\n",
      ...Object.fromEntries(built.map((item) => [`palette-${item.definition.id}.css`, `${HEADER}\n${item.css}\n`])),
    } as Record<string, string>,
    failures: built.flatMap((item) => item.failures.map((failure) => ({ palette: item.definition.id, ...failure }))),
  }
}

/** The picker's preview of one palette: its background, glass, and the text, muted and accent roles. */
function swatch(id: string, table: Map<string, string>) {
  const lines = [
    ["background", "--orchestra-background"],
    ["glass", "--orchestra-glass-background"],
    ["border", "--orchestra-glass-border"],
    ["text", "--orchestra-text"],
    ["muted", "--orchestra-muted"],
    ["accent", "--orchestra-accent"],
  ].map(([name, token]) => `  --swatch-${name}: ${table.get(token)};`)
  return [`[data-palette-swatch="${id}"] {`, ...lines, "}"].join("\n")
}

/**
 * Builds one palette: its stylesheet (one section per source file), its first-paint rules, and every text color
 * that could not reach AA without changing hue. A palette with failures does not ship.
 */
export function buildPalette(definition: PaletteDefinition, sources: Source[]) {
  const nodes = sources.map((source) => source.nodes)
  const baseTable = tokenTable(nodes, definition.scheme)
  const base = baseAnchors(baseTable)
  const remap = createRemap(base, paletteAnchors(definition.roles, base))
  const map = (property: string, value: string) => {
    if (!hasColor(value)) return value
    const mapped = remapValue(value, remap)
    if (property !== "--orchestra-workspace-overlay" || definition.roles.backdrop === undefined) return mapped
    return backdrop(mapped, definition.roles.backdrop)
  }
  const table = new Map([...baseTable].map(([name, value]) => [name, map(name, value)]))
  const reader = textReader(sources, table)
  const failures: TextCheck[] = []
  const tokens = colorTokens(nodes)
  const rules = (source: Source) =>
    paletteRules(source.nodes, {
      id: definition.id,
      scheme: definition.scheme,
      tokens,
      value: (declaration, rule) => {
        const mapped = map(declaration.property, declaration.value)
        const against = reader.surfaces(source.path, declaration, rule, (fill) => map("background", fill))
        if (!against) return mapped
        return ownLiterals(mapped).reduceRight((value, item) => {
          const color = parseColor(item.literal)
          // Pure black and white sit on fills of their own; a role token is held at AA wherever it is.
          if (!color || (extreme(color) && !ROLE_TOKENS.has(declaration.property))) return value
          const held = floor(color, against)
          if (!held)
            failures.push({
              source: source.path,
              name: declaration.property,
              value: item.literal,
              ratio: worstOver(color, against),
            })
          return value.slice(0, item.index) + formatColor(held ?? color) + value.slice(item.index + item.literal.length)
        }, mapped)
      },
    })
  const sections = sources
    .filter((source) => source.path !== "orchestra/background.css")
    .map((source) => ({ path: source.path, rules: rules(source) }))
    .filter((section) => section.rules.length > 0)
  const code = codeRule(definition, remap)
  return {
    css: [...sections.map((section) => `/* ${section.path} */\n${section.rules.join("\n")}`), code.css].join("\n"),
    firstPaint: [
      `html[data-orchestra-palette="${definition.id}"] {\n  --orchestra-palette-scheme: ${definition.scheme};\n}`,
      ...sources.filter((source) => source.path === "orchestra/background.css").flatMap(rules),
    ].join("\n"),
    swatch: swatch(definition.id, held(table, reader)),
    failures: [...failures, ...code.failures],
  }
}

/** The palette's token table with its role text colors held at AA, as the stylesheet writes them. */
function held(table: Map<string, string>, reader: ReturnType<typeof textReader>) {
  return new Map(
    [...table].map(([name, value]) => {
      const against = reader.surfaces("orchestra/theme.css", { property: name, value }, [], (fill) => fill)
      const color = colors(value)[0]
      if (!against || !color || colors(value).length !== 1) return [name, value]
      return [name, formatColor(floor(color, against) ?? color)]
    }),
  )
}

/** Every text color Orchestra's own scheme sets, with its contrast over the surface it sits on. */
export function measureBase(sources: Source[], scheme: "dark" | "light") {
  const table = tokenTable(
    sources.map((source) => source.nodes),
    scheme,
  )
  const code = codeSurface(scheme)
  return [
    ...measure(sources, sources, scheme, table),
    ...Object.entries(orchestraSyntax(scheme)).map(([name, value]) => ({
      source: CODE_SOURCE,
      name: `--syntax-${name}`,
      value,
      ratio: contrast(rgba(value), code),
    })),
  ]
}

/** Every text color a shipped palette stylesheet sets, read back from the stylesheet itself. */
export function measurePalette(sources: Source[], scheme: "dark" | "light", css: string) {
  const sections = css
    .split(/^\/\* (\S+) \*\/$/m)
    .slice(1)
    .flatMap((part, index, parts) =>
      index % 2 === 0 ? [{ path: part, nodes: unboost(parseCss(parts[index + 1])) }] : [],
    )
  const table = tokenTable(
    [...sources.map((source) => source.nodes), ...sections.map((section) => section.nodes)],
    scheme,
  )
  const codeNode = sections.flatMap((section) => section.nodes).find(isCode)
  const code = codeNode?.kind === "rule" ? codeNode.declarations : []
  const surface = rgba(code.find((item) => item.property === "--background-stronger")?.value ?? "#000")
  return [
    ...measure(sources, sections, scheme, table),
    ...code
      .filter((item) => item.property.startsWith("--syntax-"))
      .map((item) => ({
        source: CODE_SOURCE,
        name: item.property,
        value: item.value,
        ratio: contrast(rgba(item.value), surface),
      })),
  ]
}

function isCode(node: CssNode) {
  return node.kind === "rule" && node.declarations.some((item) => item.property === "--background-stronger")
}

function measure(sources: Source[], target: Source[], scheme: "dark" | "light", table: Map<string, string>) {
  const reader = textReader(sources, table)
  const checks: TextCheck[] = []
  target.forEach((source) =>
    paletteRules(source.nodes, {
      id: "measure",
      scheme,
      tokens: colorTokens([source.nodes]),
      value: (declaration, rule) => {
        const against = reader.surfaces(source.path, declaration, rule, (fill) => fill)
        if (!against) return declaration.value
        ownLiterals(declaration.value)
          .flatMap((item) => parseColor(item.literal) ?? [])
          .filter((color) => !extreme(color) || ROLE_TOKENS.has(declaration.property))
          .forEach((color) =>
            checks.push({
              source: source.path,
              name: declaration.property,
              value: formatColor(color),
              ratio: worstOver(color, against),
            }),
          )
        return declaration.value
      },
    }),
  )
  return checks
}

/** Color literals a value paints itself; a `var(--token, fallback)` fallback never shows while the token is set. */
function ownLiterals(value: string) {
  const masked = value.replace(/var\((?:[^()]|\([^()]*\))*\)/g, (match) => " ".repeat(match.length))
  return [...masked.matchAll(new RegExp(COLOR_LITERAL.source, "g"))].map((match) => ({
    index: match.index,
    literal: value.slice(match.index, match.index + match[0].length),
  }))
}

/** Strips the palette marker so shipped rules read like the source rules they override. */
function unboost(nodes: CssNode[]): CssNode[] {
  return nodes.map((node) =>
    node.kind === "at"
      ? { ...node, children: unboost(node.children) }
      : {
          ...node,
          selector: node.selector
            .replace(/(^|\n)\[data-orchestra-palette="[\w-]+"\] /g, "$1")
            .replace(/\[data-orchestra-palette="[\w-]+"\]/g, ""),
          children: unboost(node.children),
        },
  )
}

/** Decides which declarations are text colors and which surfaces each one is measured on. */
function textReader(sources: Source[], table: Map<string, string>) {
  const glass = surfaces(table)
  const used = new Set<string>()
  const visit = (nodes: CssNode[]) =>
    nodes.forEach((node) => {
      if (node.kind === "rule")
        node.declarations
          .filter((item) => item.property === "color")
          .forEach((item) => [...item.value.matchAll(/var\((--[\w-]+)/g)].forEach((match) => used.add(match[1])))
      visit(node.children)
    })
  sources.forEach((source) => visit(source.nodes))
  return {
    surfaces(source: string, declaration: Declaration, rule: Declaration[], fill: (value: string) => string) {
      const token = declaration.property.startsWith("--")
      if (token && !used.has(declaration.property) && !ROLE_TOKENS.has(declaration.property)) return
      if (!token && declaration.property !== "color") return
      const panel = SESSION_SOURCES.has(source) ? glass.session : glass.panel
      // Text on its own fill (a pill, a selected segment) is measured on that fill over the glass.
      const background = token
        ? undefined
        : rule.findLast((item) => item.property === "background" || item.property === "background-color")
      if (!background) return panel
      const resolved = background.value.replace(/var\((--[\w-]+)[^)]*\)/g, (_, name: string) => table.get(name) ?? "")
      const fills = colors(fill(resolved)).filter((color) => color.a > 0)
      return fills.length ? fills.flatMap((color) => panel.map((base) => over(color, base))) : panel
    },
  }
}

/** Orchestra's base scheme as anchors: its own token values for background, glass, text and the states. */
export function baseAnchors(table: Map<string, string>): Anchors {
  const color = (name: string, index = 0) => {
    const value = colors(table.get(name) ?? "")[index]
    if (!value) throw new Error(`Orchestra token ${name} has no color`)
    return value
  }
  return {
    background: color("--orchestra-background"),
    surface: color("--orchestra-glass-background", 1),
    muted: color("--orchestra-muted"),
    text: color("--orchestra-text"),
    accent: color("--orchestra-accent"),
    success: color("--orchestra-success"),
    warning: color("--orchestra-warm"),
    danger: color("--orchestra-danger"),
  }
}

export function paletteAnchors(roles: PaletteRoles, base: Anchors): Anchors {
  const background = rgba(roles.background)
  const text = rgba(roles.text)
  // An omitted neutral keeps the base scheme's position between its background and text.
  const between = (role: "surface" | "muted") => {
    const from = toLch(base.background).l
    const t = (toLch(base[role]).l - from) / (toLch(base.text).l - from)
    const mix = (a: number, b: number) => a + (b - a) * t
    return { r: mix(background.r, text.r), g: mix(background.g, text.g), b: mix(background.b, text.b), a: 1 }
  }
  return {
    background,
    surface: roles.surface ? rgba(roles.surface) : between("surface"),
    muted: roles.muted ? rgba(roles.muted) : between("muted"),
    text,
    accent: rgba(roles.accent),
    success: rgba(roles.success),
    warning: rgba(roles.warning),
    danger: rgba(roles.danger),
  }
}

function backdrop(value: string, share: number) {
  const [linear, ...rest] = value.split(/,\s*(?=radial-gradient)/)
  const opaque = linear.replace(new RegExp(COLOR_LITERAL.source, "g"), (literal) => {
    const color = parseColor(literal)
    return color ? formatColor({ ...color, a: 1 - (1 - color.a) * share }) : literal
  })
  return [opaque, ...rest].join(", ")
}

// Code blocks paint on the inherited `--background-stronger`. A palette moves it with its neutrals and holds
// every syntax color at AA on it.
function codeRule(definition: PaletteDefinition, remap: (color: Rgba) => Rgba) {
  // Measured as written: eight bits per channel.
  const code = parseColor(formatColor(codeSurface(definition.scheme, remap)))!
  const syntax = definition.roles.syntax ?? orchestraSyntax(definition.scheme)
  const failures: TextCheck[] = []
  const lines = Object.entries(syntax).map(([name, value]) => {
    const color = rgba(value)
    const held = floor(color, [code])
    if (!held) failures.push({ source: CODE_SOURCE, name: `--syntax-${name}`, value, ratio: contrast(color, code) })
    return `  --syntax-${name}: ${formatColor(held ?? color)};`
  })
  return {
    css: [
      `/* ${CODE_SOURCE} */`,
      `[data-orchestra-palette="${definition.id}"] body[data-new-layout] {`,
      `  --background-stronger: ${formatColor(code)};`,
      `  --color-background-stronger: ${formatColor(code)};`,
      ...lines,
      "}",
    ].join("\n"),
    failures,
  }
}

export function codeSurface(scheme: "dark" | "light", remap: (color: Rgba) => Rgba = (color) => color) {
  return remap(rgba(resolveThemeVariant(oc2Theme[scheme], scheme === "dark")["background-stronger"]))
}

/** Orchestra's own syntax colors (the inherited default theme), with its text references resolved. */
export function orchestraSyntax(scheme: "dark" | "light"): Record<string, string> {
  const resolved: Record<string, string> = resolveThemeVariant(oc2Theme[scheme], scheme === "dark")
  return Object.fromEntries(
    Object.entries(resolved)
      .filter(([name]) => name.startsWith("syntax-") && !name.startsWith("syntax-diff"))
      .map(([name, value]) => {
        const reference = /^var\(--([\w-]+)\)$/.exec(value)?.[1]
        return [name.slice("syntax-".length), reference ? (resolved[reference] ?? "") : value]
      })
      .filter(([, value]) => !!parseColor(value)),
  )
}

/**
 * Lightens or darkens a text color, keeping its hue and alpha, until it holds AA over every surface. Takes the
 * smaller lightness change (searched coarse, then fine); undefined when neither direction reaches AA.
 */
export function floor(color: Rgba, against: Rgba[]) {
  if (worstOver(color, against) >= AA) return color
  const lch = toLch(color)
  // Test each candidate as it will be written: eight bits per channel.
  const at = (delta: number) =>
    [lch.l + delta, lch.l - delta]
      .filter((l) => l >= 0 && l <= 1)
      .map((l) => parseColor(formatColor(fromLch({ ...lch, l }, color.a)))!)
      .find((next) => worstOver(next, against) >= AA)
  const steps = (from: number, to: number, step: number) =>
    Array.from({ length: Math.round((to - from) / step) + 1 }, (_, index) => from + index * step)
  const coarse = steps(0.02, 1, 0.02).find((delta) => at(delta))
  if (coarse === undefined) return undefined
  return steps(coarse - 0.018, coarse, 0.002)
    .map(at)
    .find((found) => found)
}

export function worstOver(color: Rgba, against: Rgba[]) {
  return Math.min(...against.map((surface) => contrast(color.a < 1 ? over(color, surface) : color, surface)))
}

function rgba(value: string) {
  const color = parseColor(value)
  if (!color) throw new Error(`Not a color: ${value}`)
  return color
}
