import { expect } from "bun:test"
import path from "path"
import { chmod, lstat, mkdir, mkdtemp, readFile, realpath, rm, symlink, unlink, writeFile } from "fs/promises"
import { tmpdir } from "os"
import { Effect } from "effect"
import { BackendToolkitProject } from "../src/backend-toolkit/project-version"
import openapiGenerator from "../src/backend-toolkit/packs/openapi-generator"
import { it } from "./lib/effect"

const fixture = Effect.gen(function* () {
  const directory = yield* Effect.acquireRelease(
    Effect.promise(async () => realpath(await mkdtemp(path.join(tmpdir(), "project-version-")))),
    (dir) => Effect.promise(() => rm(dir, { recursive: true, force: true })),
  )
  const project = path.join(directory, "project")
  yield* Effect.promise(() => mkdir(project))
  const write = (file: string, text: string) => Effect.promise(async () => {
    await mkdir(path.dirname(path.join(project, file)), { recursive: true })
    await writeFile(path.join(project, file), text)
  })
  const check = (argv: readonly string[] = ["generate", "-c", "openapi-generator.yaml"], cwd = project) =>
    BackendToolkitProject.checkProjectVersion({ engine: "openapi-generator", argv, cwd, projectDirectory: project }).pipe(
      Effect.match({ onSuccess: () => "allowed", onFailure: (error) => error.reason }),
    )
  yield* write("openapi-generator.yaml", "generatorName: python\ninputSpec: contract.yaml\noutputDir: generated\n")
  yield* write("contract.yaml", "openapi: 3.0.3\ninfo: {title: fixture, version: '1.0.0'}\npaths: {}\n")
  return { directory, project, write, check }
})

const mismatch = (version: string) => `engine-version-mismatch(project=${version}, bundled=${openapiGenerator.version})`

it.live("bench13 config-only generation blocks the existing output pin without changing bytes", () => Effect.gen(function* () {
  const f = yield* fixture
  yield* f.write("generated/.openapi-generator/VERSION", "7.12.0\n")
  yield* f.write("generated/client.py", "original generated bytes\n")
  const before = yield* Effect.promise(() => readFile(path.join(f.project, "generated/client.py")))
  expect(yield* f.check()).toBe(mismatch("7.12.0"))
  expect(yield* Effect.promise(() => readFile(path.join(f.project, "generated/client.py")))).toEqual(before)
}))

it.live("matching pins and true first generation proceed for YAML, JSON and equals output flags", () => Effect.gen(function* () {
  const f = yield* fixture
  expect(yield* f.check()).toBe("allowed")
  yield* f.write("generated/.openapi-generator/VERSION", `${openapiGenerator.version}\r\n`)
  yield* f.write("openapitools.json", JSON.stringify({ "generator-cli": { version: openapiGenerator.version } }))
  expect(yield* f.check()).toBe("allowed")
  yield* f.write("config.json", JSON.stringify({ outputDir: "generated" }))
  expect(yield* f.check(["generate", "--config=config.json", "--output=generated", "--dry-run"])).toBe("allowed")
  expect(yield* f.check(["generate", "-o=generated", "-i", "contract.yaml", "-g", "python"])).toBe("allowed")
}))

it.live("all declared pins matter, including project root pin from an approved subdirectory", () => Effect.gen(function* () {
  const f = yield* fixture
  yield* f.write("openapitools.json", JSON.stringify({ "generator-cli": { version: "6.6.0" } }))
  yield* f.write("generated/.openapi-generator/VERSION", `${openapiGenerator.version}\n`)
  expect(yield* f.check()).toBe(mismatch("6.6.0"))
  expect(yield* f.check(["generate", "-o", "generated", "--dry-run"])).toBe(mismatch("6.6.0"))
  yield* Effect.promise(() => mkdir(path.join(f.project, "sub")))
  expect(yield* f.check(["generate", "-o", "out"], path.join(f.project, "sub"))).toBe(mismatch("6.6.0"))
  yield* f.write("openapitools.json", JSON.stringify({ "generator-cli": { version: openapiGenerator.version } }))
  yield* f.write("generated/.openapi-generator/VERSION", "7.12.0\n")
  expect(yield* f.check()).toBe(mismatch("7.12.0"))
}))

it.live("malformed and incomplete existing metadata never becomes first generation", () => Effect.gen(function* () {
  const f = yield* fixture
  for (const content of ["", "garbage\nPRIVATE_CONTENT", "7.25.0\n7.12.0\n"]) {
    yield* f.write("generated/.openapi-generator/VERSION", content)
    expect(yield* f.check()).toBe("engine-project-version:malformed-version")
  }
  yield* Effect.promise(() => rm(path.join(f.project, "generated/.openapi-generator/VERSION")))
  expect(yield* f.check()).toBe("engine-project-version:missing-output-metadata")
  yield* Effect.promise(() => mkdir(path.join(f.project, "generated/.openapi-generator/VERSION")))
  expect(yield* f.check()).toBe("engine-project-version:malformed-output-metadata")
}))

it.live("unreadable existing metadata is a named blocker, including broken symlinks", () => Effect.gen(function* () {
  const f = yield* fixture
  yield* Effect.promise(async () => {
    await mkdir(path.join(f.project, "generated/.openapi-generator"), { recursive: true })
    await symlink(path.join(f.project, "missing-version"), path.join(f.project, "generated/.openapi-generator/VERSION"), "file")
  })
  expect(yield* f.check()).toBe("engine-project-version:unreadable-output-metadata")
  // POSIX mode bits have no Windows equivalent; Windows above exercises actual failed link resolution.
  if (process.platform === "win32") return
  yield* Effect.promise(() => rm(path.join(f.project, "generated/.openapi-generator/VERSION")))
  yield* f.write("generated/.openapi-generator/VERSION", `${openapiGenerator.version}\n`)
  yield* Effect.promise(() => chmod(path.join(f.project, "generated/.openapi-generator/VERSION"), 0))
  yield* Effect.addFinalizer(() => Effect.promise(() => chmod(path.join(f.project, "generated/.openapi-generator/VERSION"), 0o600)))
  expect(yield* f.check()).toBe("engine-project-version:unreadable-output-metadata")
}))

it.live("malformed config/project declarations and unbound or ambiguous CLI output fail closed", () => Effect.gen(function* () {
  const f = yield* fixture
  for (const content of ["outputDir: generated\noutputDir: other", "outputDir: ''"]) {
    yield* f.write("openapi-generator.yaml", content)
    expect(yield* f.check()).toBe("engine-project-version:malformed-config")
  }
  for (const content of ["outputDir: [", "- outputDir: generated"]) {
    yield* f.write("openapi-generator.yaml", content)
    expect(yield* f.check()).toBe("engine-project-version:unsupported-yaml-config")
  }
  yield* f.write("openapi-generator.yaml", "outputDir: 42")
  expect(yield* f.check()).toBe("engine-project-version:ambiguous-yaml-scalar:outputDir")
  yield* f.write("openapi-generator.yaml", "generatorName: python\n")
  expect(yield* f.check()).toBe("engine-project-version:unbound-output")
  yield* f.write("openapi-generator.yaml", "outputDir: '${OUTPUT}'\n")
  expect(yield* f.check()).toBe("engine-project-version:unbound-output")
  expect(yield* f.check(["generate", "-c", "${CONFIG}"])).toBe("engine-project-version:unbound-config")
  expect(yield* f.check(["generate", "-c", "missing.yaml"])).toBe("engine-project-version:missing-config")
  expect(yield* f.check(["generate", "-o"])).toBe("engine-project-version:unbound-args")
  expect(yield* f.check(["generate", "-o", "one", "--output=two"])).toBe("engine-project-version:conflicting-output")
  expect(yield* f.check(["generate", "-c", "one", "--config=two"])).toBe("engine-project-version:conflicting-config")
  expect(yield* f.check(["generate", "--dry-run=false", "-o", "out"])).toBe("engine-project-version:unsupported-owned-call")
  expect(yield* f.check(["batch", "generation.yaml"])).toBe("engine-project-version:unsupported-owned-call")
  yield* f.write("openapi-generator.yaml", "outputDir: generated\n")
  expect(yield* f.check(["generate", "-c", "openapi-generator.yaml", "--output=other"])).toBe("engine-project-version:conflicting-output")
  for (const content of ["{", "[]", '{"generator-cli":{"version":42}}', '{"generator-cli":"bad"}', '{"generator-cli":{"version":"7.25.0","version":"7.12.0"}}']) {
    yield* f.write("openapitools.json", content)
    expect(yield* f.check()).toMatch(/^engine-project-version:malformed-(project-metadata|version)$/)
  }
}))

it.live("YAML aliases cannot substitute an old output behind matching generated metadata", () => Effect.gen(function* () {
  const f = yield* fixture
  yield* f.write("generated/.openapi-generator/VERSION", `${openapiGenerator.version}\n`)
  yield* f.write("old/.openapi-generator/VERSION", "7.10.0\n")
  yield* f.write("openapi-generator.yaml", "checked: &checked generated\nselected: &old old\noutputDir: *old\ninputSpec: contract.yaml\n")
  expect(yield* f.check()).toBe("engine-project-version:unsupported-yaml-config")
  for (const content of [
    "base: &base\n  outputDir: old\n<<: *base\noutputDir: generated\n",
    "%YAML 1.1\n---\noutputDir: generated\n", "outputDir: !!str generated\n",
    "outputDir: !local generated\n", "outputDir: |\n  generated\n", "outputDir: {name: generated}\n",
  ]) {
    yield* f.write("openapi-generator.yaml", content)
    expect(yield* f.check()).toBe("engine-project-version:unsupported-yaml-config")
  }
  expect(yield* Effect.promise(() => readFile(path.join(f.project, "old/.openapi-generator/VERSION"), "utf8"))).toBe("7.10.0\n")
}))
