import { expect, test } from "bun:test"
import { join } from "node:path"
import { unlink, symlink } from "node:fs/promises"
import { recoveryBegin, recoveryPrepare, recoveryRestore } from "../src/governance/recovery.ts"
import { fixture, operation, check, capture } from "./fixtures.governance.ts"
import { rethrow } from "./rejection.ts"
test("selective recovery restores committed owned file; preserves user dirt, untracked, HEAD/index", async () => {
  const f = await fixture()
  const baseline = await f.init()
  expect(await operation({ operation: "recovery-begin", wave: "wave", ownedPaths: ["owned.ts"] }, f.context)).toMatchObject({ baseline, globalAtomicTransaction: false })
  await Bun.write(join(f.root, "owned.ts"), "export const value = 9\n")
  await Bun.write(join(f.root, "other.ts"), "user dirt\n")
  await Bun.write(join(f.root, "user.txt"), "untracked user content\n")
  const index = await f.runGit("write-tree")
  const plan = await operation<{ token: string }>({ operation: "recovery-prepare", wave: "wave" }, f.context)
  expect(await operation({ operation: "recovery-restore", token: plan.token }, f.context)).toMatchObject({ status: "RESTORED_OWNED_FILES", restored: ["owned.ts"], globalAtomicTransaction: false, externalEffectsReversed: false })
  expect(await Bun.file(join(f.root, "owned.ts")).text()).toBe("export const value = 1\n")
  expect(await Bun.file(join(f.root, "other.ts")).text()).toBe("user dirt\n")
  expect(await Bun.file(join(f.root, "user.txt")).text()).toBe("untracked user content\n")
  expect(await f.runGit("rev-parse", "HEAD")).toBe(baseline)
  expect(await f.runGit("write-tree")).toBe(index)
  expect(await operation({ operation: "recovery-status", wave: "wave" }, f.context)).toMatchObject({ baseline })
})
test("recovery refuses concurrent dirt changes after prepare", async () => {
  const f = await fixture()
  await f.init()
  await recoveryBegin(f.context, f.root, "wave", ["owned.ts"])
  await Bun.write(join(f.root, "owned.ts"), "wave dirt\n")
  const plan = await recoveryPrepare(f.context, f.root, "wave")
  await Bun.write(join(f.root, "other.ts"), "concurrent user edit\n")
  expect(await rethrow(recoveryRestore(f.context, f.root, plan.token))).toThrow("RECOVERY_CONCURRENT_HEAD_OR_DIRT_CHANGED")
  expect(await Bun.file(join(f.root, "owned.ts")).text()).toBe("wave dirt\n")
})
test("recovery refuses concurrent HEAD changes after prepare", async () => {
  const f = await fixture()
  await f.init()
  await recoveryBegin(f.context, f.root, "wave", ["owned.ts"])
  await Bun.write(join(f.root, "owned.ts"), "wave dirt\n")
  const plan = await recoveryPrepare(f.context, f.root, "wave")
  await Bun.write(join(f.root, "other.ts"), "new committed head\n")
  await f.runGit("add", "other.ts")
  await f.runGit("commit", "-m", "fix: concurrent head")
  expect(await rethrow(recoveryRestore(f.context, f.root, plan.token))).toThrow("RECOVERY_CONCURRENT_HEAD_OR_DIRT_CHANGED")
  expect(await Bun.file(join(f.root, "owned.ts")).text()).toBe("wave dirt\n")
})
test("recovery native edit denial prevents restore and ownership cannot include untracked/dirty files", async () => {
  const f = await fixture()
  await f.init()
  await Bun.write(join(f.root, "untracked.ts"), "user file\n")
  expect(await rethrow(recoveryBegin(f.context, f.root, "bad", ["untracked.ts"]))).toThrow("RECOVERY_NOT_COMMITTED_REGULAR_FILE")
  await recoveryBegin(f.context, f.root, "wave", ["owned.ts"])
  await Bun.write(join(f.root, "owned.ts"), "wave dirt\n")
  expect(await rethrow(recoveryBegin(f.context, f.root, "dirty", ["owned.ts"]))).toThrow("RECOVERY_BASELINE_OWNED_FILE_DIRTY")
  const plan = await recoveryPrepare(f.context, f.root, "wave")
  expect(await rethrow(recoveryRestore({ ...f.context, async authorize(request) { if (request.effect === "write") throw new Error("HOST_EDIT_DENIED") } }, f.root, plan.token))).toThrow("HOST_EDIT_DENIED")
  expect(await Bun.file(join(f.root, "owned.ts")).text()).toBe("wave dirt\n")
})
test("recovery replay uses actual status, preserves green and names missing/skips for retry", async () => {
  const f = await fixture()
  expect(await operation({ operation: "recovery-replay", requiredChecks: ["green", "skip", "missing"], checks: capture(check("green"), check("skip", "skip")) }, f.context)).toMatchObject({ retryChecks: ["skip", "missing"], preservedGreen: ["green"], dispatched: false })
})
test("recovery re-creates deleted committed owned file and rejects symlink substitution", async () => {
  const f = await fixture()
  await f.init()
  await recoveryBegin(f.context, f.root, "wave", ["owned.ts"])
  await unlink(join(f.root, "owned.ts"))
  const plan = await recoveryPrepare(f.context, f.root, "wave")
  await recoveryRestore(f.context, f.root, plan.token)
  expect(await Bun.file(join(f.root, "owned.ts")).text()).toBe("export const value = 1\n")
  await unlink(join(f.root, "owned.ts"))
  await Bun.write(join(f.state, "outside.ts"), "outside user file\n")
  await symlink(join(f.state, "outside.ts"), join(f.root, "owned.ts"))
  expect(await rethrow(recoveryPrepare(f.context, f.root, "wave"))).toThrow("PATH_SYMLINK_DENIED")
  expect(await Bun.file(join(f.state, "outside.ts")).text()).toBe("outside user file\n")
})
test("recovery restores binary blobs byte-for-byte without text decoding", async () => {
  const f = await fixture()
  await f.init()
  const bytes = Buffer.from([0, 255, 254, 128, 13, 10, 42])
  await Bun.write(join(f.root, "owned.bin"), bytes)
  await f.runGit("add", "owned.bin")
  await f.runGit("commit", "-m", "test: binary baseline")
  await recoveryBegin(f.context, f.root, "wave", ["owned.bin"])
  await Bun.write(join(f.root, "owned.bin"), Buffer.from([0, 1]))
  const plan = await recoveryPrepare(f.context, f.root, "wave")
  await recoveryRestore(f.context, f.root, plan.token)
  expect(Buffer.from(await Bun.file(join(f.root, "owned.bin")).arrayBuffer())).toEqual(bytes)
})
test("recovery ownership refuses git metadata under either separator and its NTFS aliases before any read", async () => {
  const f = await fixture()
  await f.init()
  // Pure string refusal, so it holds on every OS; on Windows these spellings open the real .git directory.
  await Promise.all([".git\\config", "sub\\.git\\HEAD", ".GIT/config", "git~1\\config", ".git.\\config", "C:.git\\config", "\\\\server\\share\\owned.ts"].map(async (path) =>
    expect(await rethrow(recoveryBegin(f.context, f.root, "wave", [path]))).toThrow("RECOVERY_GIT_METADATA_DENIED")))
  expect(f.permissions.some((request) => request.effect === "read")).toBe(false)
})
test("recovery restores an owned file in a subdirectory", async () => {
  const f = await fixture()
  await f.init()
  await Bun.write(join(f.root, "src", "nested.ts"), "export const nested = 1\n")
  await f.runGit("add", "src/nested.ts")
  await f.runGit("commit", "-m", "test: nested baseline")
  await recoveryBegin(f.context, f.root, "wave", ["src/nested.ts"])
  await Bun.write(join(f.root, "src", "nested.ts"), "wave dirt\n")
  const plan = await recoveryPrepare(f.context, f.root, "wave")
  // Git lists the temporary restore file with "/"; only Windows spells it differently natively.
  expect(await recoveryRestore(f.context, f.root, plan.token)).toMatchObject({ restored: ["src/nested.ts"] })
  expect(await Bun.file(join(f.root, "src", "nested.ts")).text()).toBe("export const nested = 1\n")
})
