import { expect, test } from "bun:test"
import { mkdir, symlink } from "node:fs/promises"
import { join } from "node:path"
import { changeBudget, changedFiles, selectCI, changelog, releaseProposal } from "../src/governance/repository.ts"
import { fixture, operation, capture, check } from "./fixtures.governance.ts"
import { processOutput, PROCESS_BYTES } from "../src/governance/process.ts"

test("budget acquires real Git diff/untracked data, partitions reviewers and fails actual hard cap", async () => {
  const f = await fixture()
  await f.init()
  await Bun.write(join(f.root, "owned.ts"), "export const value = 2\nexport const second = 3\n")
  await Bun.write(join(f.root, "new.ts"), "export const fresh = true\n")
  const report = await operation<{ codeLines: number; status: string; reviewerPartitions: { paths: string[]; lines: number }[] }>({ operation: "change-budget", soft: 1, hard: 2, reviewerCap: 2 }, f.context)
  expect(report.codeLines).toBe(4)
  expect(report.status).toBe("FAIL")
  expect(report.reviewerPartitions.flatMap((part) => part.paths).sort()).toEqual(["new.ts", "owned.ts"])
  expect(await changeBudget(f.context, f.root, { soft: 10, hard: 20 })).toMatchObject({ status: "PASS", codeLines: 4 })
  await expect(changeBudget(f.context, f.root, { excludedPaths: ["not-changed.ts"] })).rejects.toThrow("CHANGE_BUDGET_STALE_EXCLUSION")
})
test("Git launch/acquisition failure, missing dev baseline and binary changes remain named", async () => {
  const f = await fixture()
  await expect(changedFiles(f.context, f.root)).rejects.toThrow("PROCESS_ACQUISITION_FAILED")
  await f.init()
  await expect(changedFiles(f.context, f.root, "missing")).rejects.toThrow("PROCESS_ACQUISITION_FAILED")
  await Bun.write(join(f.root, "binary.dat"), Buffer.from([0, 1, 2]))
  const report = await changeBudget(f.context, f.root, {})
  expect(report.status).toBe("HOLD")
  expect(report.failures).toContain("BINARY_CHANGE_UNMEASURED: binary.dat")
})
test("native process denial prevents Git acquisition instead of empty report", async () => {
  const f = await fixture()
  await f.init()
  await expect(operation({ operation: "change-budget" }, { ...f.context, async authorize(request) { if (request.effect === "process") throw new Error("HOST_PROCESS_DENIED") } })).rejects.toThrow("HOST_PROCESS_DENIED")
})
test("repository-wide acquisition refuses context rooted at subdirectory", async () => {
  const f = await fixture()
  await f.init()
  const nested = join(f.root, "nested")
  await mkdir(nested)
  await expect(operation({ operation: "change-budget" }, { ...f.context, directory: nested })).rejects.toThrow("GIT_REPOSITORY_ROOT_OUTSIDE_CONTEXT")
})
test("actual process launch and bounded-output acquisition errors are named", async () => {
  const f = await fixture()
  await expect(processOutput(f.context, f.root, [join(f.directory, "missing-executable")])).rejects.toThrow("PROCESS_LAUNCH_FAILED")
  expect(await processOutput(f.context, f.root, [process.execPath, "-e", "process.stdout.write('actual observation')"])).toBe("actual observation")
  await expect(processOutput(f.context, f.root, [process.execPath, "-e", `process.stdout.write('x'.repeat(${PROCESS_BYTES + 1}))`])).rejects.toThrow("PROCESS_OUTPUT_OVERFLOW")
})
test("CI uses actual changed paths and explicit groups, unmatched/config paths select FULL", async () => {
  const f = await fixture()
  await f.init()
  await Bun.write(join(f.root, "owned.ts"), "export const value = 2\n")
  const groups = [{ prefix: "owned.ts", group: "CORE" }]
  const universal = ["commitlint", "change-budget"]
  expect(await operation({ operation: "ci-select", groups, universal }, f.context)).toMatchObject({ selection: "SCOPED", groups: ["CORE"] })
  expect(selectCI(["unknown.xyz"], groups, universal).selection).toBe("FULL")
  expect(selectCI(["package.json"], groups, universal).selection).toBe("FULL")
  expect(selectCI(["README.md"], groups, universal).selection).toBe("UNIVERSAL_ONLY")
  expect(selectCI([], groups, universal).selection).toBe("FULL")
  expect(() => selectCI(["owned.ts"], [], universal)).toThrow("CI_RULES_OR_UNIVERSAL_EMPTY")
})
test("metrics read exact scope, LOC gate red/green, unreadable/empty/escape acquisition named", async () => {
  const f = await fixture()
  await f.init()
  expect(await operation({ operation: "metrics-snapshot", paths: ["owned.ts", "other.ts"] }, f.context)).toMatchObject({ totalLoc: 2, completeForRequestedPaths: true })
  expect(await operation({ operation: "loc-cap", paths: ["owned.ts"], threshold: 1 }, f.context)).toMatchObject({ status: "PASS" })
  await Bun.write(join(f.root, "owned.ts"), "one\ntwo\n")
  expect(await operation({ operation: "loc-cap", paths: ["owned.ts"], threshold: 1 }, f.context)).toMatchObject({ status: "FAIL", failures: ["LOC_CAP_EXCEEDED: owned.ts"] })
  await expect(operation({ operation: "metrics-snapshot", paths: [] }, f.context)).rejects.toThrow("METRICS_PATHS_EMPTY_OR_INVALID")
  await expect(operation({ operation: "metrics-snapshot", paths: ["missing.ts"] }, f.context)).rejects.toThrow("STATE_READ_FAILED: ENOENT")
  await expect(operation({ operation: "metrics-snapshot", paths: ["../escape"] }, f.context)).rejects.toThrow("PATH_ESCAPE")
  await symlink(join(f.state, "secret"), join(f.root, "link"))
  await expect(operation({ operation: "metrics-snapshot", paths: ["link"] }, f.context)).rejects.toThrow("PATH_SYMLINK_DENIED")
  expect(await operation({ operation: "metrics-report", metricsBaseline: { files: [{ path: "owned.ts", loc: 4 }] }, metricsFinal: { files: [{ path: "owned.ts", loc: 2 }] } }, f.context)).toMatchObject({ reductionPercent: 50, correctnessClaim: false })
})
test("changelog gate checks actual parsed package/version/body; proposals remain uncurated", async () => {
  const f = await fixture()
  await f.init()
  expect(await operation({ operation: "changelog-check", packagePath: "package.json", changelogPath: "CHANGELOG.md" }, f.context)).toMatchObject({ status: "PASS" })
  const proposal = await operation<{ entry: string; written: boolean }>({ operation: "changelog-propose", version: "1.0.0", title: "Release", date: "2026-09-30" }, f.context)
  expect(proposal.written).toBe(false)
  await Bun.write(join(f.root, "CHANGELOG.md"), proposal.entry)
  expect((await changelog(f.context, f.root, "package.json", "CHANGELOG.md")).failures).toContain("CHANGELOG_UNCURATED")
  await Bun.write(join(f.root, "CHANGELOG.md"), "# no release section\n")
  await expect(changelog(f.context, f.root, "package.json", "CHANGELOG.md")).rejects.toThrow("CHANGELOG_SECTION_MISSING")
  await Bun.write(join(f.root, "package.json"), JSON.stringify({ version: null }))
  await expect(changelog(f.context, f.root, "package.json", "CHANGELOG.md")).rejects.toThrow("PACKAGE_VERSION_MISSING_OR_INVALID")
})
test("release validates actual HEAD/checks/changelog/dev/tag; never creates tag or publishes", async () => {
  const f = await fixture()
  const head = await f.init()
  const input = { packagePath: "package.json", changelogPath: "CHANGELOG.md", checks: capture(check("FULL", "pass", head)), requiredChecks: ["FULL"] }
  expect(await operation({ operation: "release-propose", ...input }, f.context)).toMatchObject({ status: "LOCAL_READY", branch: "dev", executed: false })
  expect(await f.runGit("tag", "--list")).toBe("")
  expect((await releaseProposal(f.context, f.root, { ...input, checks: capture(check("FULL", "skip", head)) })).failures).toContain("RELEASE_CHECK_SKIP: FULL")
  expect((await releaseProposal(f.context, f.root, { ...input, checks: capture(check("OTHER", "pass", head)) })).failures).toContain("RELEASE_CHECK_MISSING: FULL")
  await Bun.write(join(f.root, "owned.ts"), "changed\n")
  expect((await releaseProposal(f.context, f.root, input)).failures).toContain("RELEASE_DIRTY_TREE")
})
test("ruleset proposal uses explicit repository/dev/status checks, makes no cloud calls", async () => {
  const f = await fixture()
  const proposal = await operation<{ body: { conditions: { ref_name: { include: string[] } }; rules: { type: string }[] }; executed: boolean }>({ operation: "ruleset-propose", repository: "owner/project", requiredStatusChecks: ["verify"] }, f.context)
  expect(proposal.body.conditions.ref_name.include).toEqual(["refs/heads/dev"])
  expect(proposal.body.rules.map((rule) => rule.type)).toContain("required_status_checks")
  expect(proposal.executed).toBe(false)
  expect(f.permissions.length).toBe(0)
})
test("policy/sandbox proposals scope real paths but cannot grant or claim kernel enforcement", async () => {
  const f = await fixture()
  await f.init()
  for (const operationName of ["policy-propose", "sandbox-propose"] as const) {
    expect(await operation({ operation: operationName, policy: { ownedPaths: ["owned.ts"], denyPaths: ["other.ts"], allowedDomains: ["github.com"] } }, f.context)).toMatchObject({ permissionGranted: false, sandboxRunning: false, writes: [join(f.root, "owned.ts")] })
  }
  expect(f.permissions.every((request) => request.effect === "read")).toBe(true)
  await expect(operation({ operation: "policy-propose", policy: { ownedPaths: ["../escape"], denyPaths: [], allowedDomains: [] } }, f.context)).rejects.toThrow("PATH_ESCAPE")
})
test("preflight actual captures arm/check/disarm; failed rearm revokes earlier green", async () => {
  const f = await fixture()
  const head = await f.init()
  expect(await operation({ operation: "preflight-arm", wave: "wave", checks: capture(check("smoke", "pass", head)), requiredChecks: ["smoke"] }, f.context)).toMatchObject({ armed: true })
  expect(await operation({ operation: "preflight-check", wave: "wave" }, f.context)).toMatchObject({ status: "PASS" })
  expect(await operation({ operation: "preflight-disarm", wave: "wave" }, f.context)).toMatchObject({ armed: false })
  expect(await operation({ operation: "preflight-check", wave: "wave" }, f.context)).toMatchObject({ status: "FAIL", failures: ["PREFLIGHT_NOT_ARMED"] })
  const failed = await operation<{ armed: boolean; failures: string[] }>({ operation: "preflight-arm", wave: "wave", checks: capture(check("smoke", "skip", head)), requiredChecks: ["smoke"] }, f.context)
  expect(failed.armed).toBe(false)
  expect(failed.failures).toContain("PREFLIGHT_CHECK_SKIP: smoke")
  expect(await operation({ operation: "preflight-check", wave: "wave" }, f.context)).toMatchObject({ status: "FAIL", failures: ["PREFLIGHT_NOT_ARMED", "PREFLIGHT_CHECK_SKIP: smoke"] })
})
test("commitlint reads actual Git commit messages and detects invalid subjects", async () => {
  const f = await fixture()
  await f.init()
  await f.runGit("checkout", "-b", "work")
  await Bun.write(join(f.root, "owned.ts"), "export const value = 2\n")
  await f.runGit("add", "owned.ts")
  await f.runGit("commit", "-m", "fix: preserved contract")
  expect(await operation({ operation: "commitlint" }, f.context)).toMatchObject({ status: "PASS" })
  await Bun.write(join(f.root, "owned.ts"), "export const value = 3\n")
  await f.runGit("add", "owned.ts")
  await f.runGit("commit", "-m", "bad subject")
  expect(await operation({ operation: "commitlint" }, f.context)).toMatchObject({ status: "FAIL" })
})
