export * as CapabilityAssetCatalog from "./catalog"

import { CapabilityAssetSources } from "./sources"

export { providers } from "./providers"

// Destination references reserve paths for later source imports; they are not executable registrations.
export const all = [
  { id: "A01", kind: "skill", originalName: "har-derived-api-client", skillName: "api-discovery", bodyName: "api-discovery",
    nativeNames: ["api_capture", "api_inspect"], status: "source-qualified", destination: "assets/skills/api-discovery/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-skills/web-development/har-derived-api-client/SKILL.md"] } },
  { id: "A02", kind: "skill", originalName: "google-workspace", skillName: "office-operations", bodyName: "office-operations",
    nativeNames: ["mail_read", "mail_send", "mail_update", "calendar_read", "calendar_update", "drive_read", "drive_update", "document_read", "document_edit", "sheet_read", "sheet_edit", "service_call"],
    status: "source-qualified", destination: "assets/skills/office-operations/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["skills/productivity/google-workspace/SKILL.md"] } },
  { id: "A03", kind: "skill", originalName: "pdf", skillName: "document-pdf", bodyName: "document-pdf",
    nativeNames: ["document_read", "document_edit"], status: "source-qualified", destination: "assets/skills/document-pdf/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["skills/productivity/pdf/SKILL.md"] } },
  { id: "A04", kind: "skill", originalName: "xlsx", skillName: "document-sheets", bodyName: "document-sheets",
    nativeNames: ["sheet_read", "sheet_edit"], status: "source-qualified", destination: "assets/skills/document-sheets/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["skills/productivity/xlsx/SKILL.md"] } },
  { id: "A05", kind: "skill", originalName: "github", skillName: "github-operations", bodyName: "github-operations",
    nativeNames: ["service_find", "service_describe", "service_call"], status: "source-qualified", destination: "assets/skills/github-operations/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["skills/software-development/github/SKILL.md"] },
    additionalUpstreams: [{ ...CapabilityAssetSources.openclaw, paths: ["skills/github/SKILL.md"] }] },
  { id: "A06", kind: "skill", originalName: "publish-site", skillName: "site-publish", bodyName: "site-publish",
    nativeNames: ["service_call"], status: "source-qualified", destination: "assets/skills/site-publish/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-skills/web-development/publish-site/SKILL.md"] } },
  { id: "A07", kind: "skill", originalName: "cloudflare-temporary-deploy", skillName: "edge-preview", bodyName: "edge-preview",
    nativeNames: ["service_call"], status: "source-qualified", destination: "assets/skills/edge-preview/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-skills/web-development/cloudflare-temporary-deploy/SKILL.md"] } },
  { id: "A08", kind: "skill", originalName: "stripe-projects", skillName: "stack-provision", bodyName: "stack-provision",
    nativeNames: ["service_find", "service_describe", "service_call"], status: "source-qualified", destination: "assets/skills/stack-provision/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-skills/payments/stripe-projects/SKILL.md"] } },
  { id: "A09", kind: "skill", originalName: "watchers", skillName: "resource-watch", bodyName: "resource-watch",
    nativeNames: ["schedule_manage", "service_call"], status: "source-qualified", destination: "assets/skills/resource-watch/SKILL.md",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-skills/devops/watchers/SKILL.md"] } },
  { id: "A10", kind: "skill", originalName: "notion", skillName: "notion-operations", bodyName: "notion-operations",
    nativeNames: ["page_read", "page_update"], status: "source-qualified", destination: "assets/skills/notion-operations/SKILL.md",
    upstream: { ...CapabilityAssetSources.openclaw, paths: ["skills/notion/SKILL.md"] } },
  { id: "A11", kind: "skill", originalName: "himalaya", skillName: "mail-operations", bodyName: "mail-operations",
    nativeNames: ["mail_read", "mail_send", "mail_update"], status: "source-qualified", destination: "assets/skills/mail-operations/SKILL.md",
    upstream: { ...CapabilityAssetSources.openclaw, paths: ["skills/himalaya/SKILL.md"] } },
  { id: "A12", kind: "skill", originalName: "mcporter", skillName: "mcp-client-build", bodyName: "mcp-client-build",
    nativeNames: ["service_call"], status: "source-qualified", destination: "assets/skills/mcp-client-build/SKILL.md",
    upstream: { ...CapabilityAssetSources.openclaw, paths: ["skills/mcporter/SKILL.md"] },
    additionalUpstreams: [{ ...CapabilityAssetSources.hermes, paths: ["optional-skills/mcp/mcporter/SKILL.md"] }] },
  { id: "A13", kind: "provider", originalName: "cloudflare", nativeNames: ["platform.cloudflare"], status: "source-qualified",
    destination: "assets/providers/cloudflare.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/cloudflare/manifest.yaml"] } },
  { id: "A14", kind: "provider", originalName: "supabase", nativeNames: ["platform.supabase"], status: "source-qualified",
    destination: "assets/providers/supabase.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/supabase/manifest.yaml"] } },
  { id: "A15", kind: "provider", originalName: "vercel", nativeNames: ["platform.vercel"], status: "source-qualified",
    destination: "assets/providers/vercel.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/vercel/manifest.yaml"] } },
  { id: "A16", kind: "provider", originalName: "neon", nativeNames: ["platform.neon"], status: "source-qualified",
    destination: "assets/providers/neon.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/neon/manifest.yaml"] } },
  { id: "A17", kind: "provider", originalName: "railway", nativeNames: ["platform.railway"], status: "source-qualified",
    destination: "assets/providers/railway.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/railway/manifest.yaml"] } },
  { id: "A18", kind: "provider", originalName: "sentry", nativeNames: ["platform.sentry"], status: "source-qualified",
    destination: "assets/providers/sentry.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/sentry/manifest.yaml"] } },
  { id: "A19", kind: "provider", originalName: "grafana", nativeNames: ["platform.grafana"], status: "source-qualified",
    destination: "assets/providers/grafana.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/grafana/manifest.yaml"] } },
  { id: "A20", kind: "provider", originalName: "globalping", nativeNames: ["platform.globalping"], status: "source-qualified",
    destination: "assets/providers/globalping.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/globalping/manifest.yaml"] } },
  { id: "A21", kind: "provider", originalName: "linear", nativeNames: ["platform.linear"], status: "source-qualified",
    destination: "assets/providers/linear.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/linear/manifest.yaml"] } },
  { id: "A22", kind: "provider", originalName: "stripe", nativeNames: ["platform.stripe"], status: "source-qualified",
    destination: "assets/providers/stripe.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/stripe/manifest.yaml"] } },
  { id: "A23", kind: "provider", originalName: "netlify", nativeNames: ["platform.netlify"], status: "source-qualified",
    destination: "assets/providers/netlify.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/netlify/manifest.yaml"] } },
  { id: "A24", kind: "provider", originalName: "prisma-postgres", nativeNames: ["platform.prisma-postgres"], status: "source-qualified",
    destination: "assets/providers/prisma-postgres.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["optional-mcps/prisma-postgres/manifest.yaml"] } },
  { id: "A25", kind: "native", originalName: "message", nativeNames: ["channel_read", "channel_send", "channel_update"],
    status: "source-qualified", destination: "assets/native/channel/manifest.json",
    upstream: { ...CapabilityAssetSources.openclaw, paths: ["src/channels/plugins/message-tool-api.ts", "extensions/slack/message-tool-api.ts", "extensions/discord/action-runtime-api.ts"] } },
  { id: "A26", kind: "native", originalName: "image_generate", nativeNames: ["image_create"],
    status: "source-qualified", destination: "assets/native/image-create/manifest.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["tools/image_generation_tool.py"] },
    additionalUpstreams: [{ ...CapabilityAssetSources.openclaw, paths: ["extensions/openai/image-generation-provider.ts"] }] },
  { id: "A27", kind: "native", originalName: "video_generate", nativeNames: ["video_create"],
    status: "source-qualified", destination: "assets/native/video-create/manifest.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["tools/video_generation_tool.py"] },
    additionalUpstreams: [{ ...CapabilityAssetSources.openclaw, paths: ["extensions/runway/video-generation-provider.ts"] }] },
  { id: "A28", kind: "native", originalName: "show_widget", nativeNames: ["artifact_show"],
    status: "source-qualified", destination: "assets/native/artifact-show/manifest.json",
    upstream: { ...CapabilityAssetSources.openclaw, paths: ["src/canvas/widget-tool.ts"] } },
  { id: "A29", kind: "native", originalName: "pdf", nativeNames: ["document_read"],
    status: "source-qualified", destination: "assets/native/document-extract/manifest.json",
    upstream: { ...CapabilityAssetSources.openclaw, paths: ["extensions/document-extract/document-extractor.ts", "extensions/document-extract/document-extractor.worker.ts"] } },
  { id: "A30", kind: "native", originalName: "onepassword", nativeNames: ["vault_list", "vault_bind"],
    status: "source-qualified", destination: "assets/native/vault/manifest.json",
    upstream: { ...CapabilityAssetSources.openclaw, paths: ["extensions/onepassword/onepassword-secret-ref-resolver.js", "skills/1password/SKILL.md"] } },
  { id: "A31", kind: "native", originalName: "process_manage", nativeNames: ["process_control"],
    status: "source-qualified", destination: "assets/native/process-control/manifest.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["tools/process_registry.py", "tools/process_registry_results.py"] } },
  { id: "A32", kind: "native", originalName: "cronjob_manage", nativeNames: ["schedule_manage"],
    status: "source-qualified", destination: "assets/native/schedule/manifest.json",
    upstream: { ...CapabilityAssetSources.hermes, paths: ["tools/cronjob_tools.py"] } },
] as const
