// Transcribed from the pinned Hermes manifests in the catalog. Filters are upstream presets,
// not executable entrypoints, discovered tool schemas, permissions or qualification receipts.
export const providers = [
  { assetID: "A13", endpoint: "https://mcp.cloudflare.com/mcp?codemode=false", transport: "http", auth: "oauth",
    defaultExcluded: [
      "docs", "*_radar_*", "*_accounts_magic_*", "*_accounts_mnm_*", "*_accounts_cni_*", "*_accounts_teamnet_*",
      "*_accounts_cloudforceone_*", "*_accounts_dlp_*", "*_accounts_devices*", "*_accounts_dex_*",
      "*_accounts_datasecurity_*", "*_accounts_emailsecurity_*", "*_accounts_scim_*", "*_accounts_gateway*",
      "*_accounts_zerotrust_*", "*_accounts_one_*", "*_accounts_brandprotection_*", "*_accounts_intel_*",
      "*_accounts_urlscanner_*", "*_accounts_vuln_scanner_*", "*_zones_securitycenter_*", "*_accounts_securitycenter_*",
      "*_zones_api_gateway_*", "*_zones_schema_validation*", "*_zones_token_validation*", "*_zones_waiting_rooms*",
      "*_accounts_addressing_*", "*_accounts_shares*", "*_accounts_slurper_*", "*_zones_web3_*",
      "*_accounts_flagship_*", "*_zones_secondary_dns_*", "*_accounts_secondary_dns_*", "*_user_load_balancers*",
    ] },
  { assetID: "A14", endpoint: "https://mcp.supabase.com/mcp", transport: "http", auth: "oauth", defaultExcluded: [] },
  { assetID: "A15", endpoint: "https://mcp.vercel.com", transport: "http", auth: "oauth", defaultExcluded: [] },
  { assetID: "A16", endpoint: "https://mcp.neon.tech/mcp", transport: "http", auth: "oauth",
    defaultExcluded: ["search", "fetch", "list_docs_resources", "get_doc_resource", "query_logs", "list_log_fields",
      "list_log_field_values", "provision_neon_auth", "configure_neon_auth", "get_neon_auth_config"] },
  { assetID: "A17", endpoint: "https://mcp.railway.com", transport: "http", auth: "oauth", defaultExcluded: ["railway-agent"] },
  { assetID: "A18", endpoint: "https://mcp.sentry.dev/mcp", transport: "http", auth: "oauth", defaultExcluded: [] },
  { assetID: "A19", endpoint: "https://mcp.grafana.com/mcp", transport: "http", auth: "oauth",
    defaultExcluded: ["ask_assistant", "agento11y_*"] },
  { assetID: "A20", endpoint: "https://mcp.globalping.dev/mcp", transport: "http", auth: "oauth",
    defaultExcluded: ["help", "compareLocations", "limits"] },
  { assetID: "A21", endpoint: "https://mcp.linear.app/mcp", transport: "http", auth: "oauth", defaultExcluded: [] },
  { assetID: "A22", endpoint: "https://mcp.stripe.com", transport: "http", auth: "oauth", defaultExcluded: [] },
  { assetID: "A23", endpoint: "https://netlify-mcp.netlify.app/mcp", transport: "http", auth: "oauth", defaultExcluded: [] },
  { assetID: "A24", endpoint: "https://mcp.prisma.io/mcp", transport: "http", auth: "oauth",
    defaultExcluded: ["search_prisma_documentation"] },
] as const
