// Generated by @orchestra/httpapi-codegen. Do not edit.
import { Effect } from "effect"
import { HttpClient, HttpClientRequest } from "effect/unstable/http"
import { HttpApi, HttpApiClient } from "effect/unstable/httpapi"
import { adaptGroup0, Group0 } from "./probe"

const Api = HttpApi.make("generated").add(Group0)
const adaptClient = (raw: HttpApiClient.ForApi<typeof Api>) => ({ probe: adaptGroup0(raw["probe"]) })

export const make = (options?: {
  readonly baseUrl?: URL | string
  readonly headers?: Readonly<Record<string, string>>
}) => {
  if (options?.headers === undefined) return HttpApiClient.make(Api, options).pipe(Effect.map(adaptClient))
  // Snapshot and validate host configuration now, before this Effect can be executed or reused.
  const headers = Object.freeze(Object.fromEntries(new Headers(options.headers)))
  if (Object.keys(headers).length === 0) return HttpApiClient.make(Api, options).pipe(Effect.map(adaptClient))
  return HttpApiClient.make(Api, {
    baseUrl: options.baseUrl,
    transformClient: (client) =>
      HttpClient.mapRequest(client, (request) =>
        HttpClientRequest.setHeaders(request, { ...headers, ...request.headers }),
      ),
  }).pipe(Effect.map(adaptClient))
}
