// Generated by @orchestra/httpapi-codegen. Do not edit.
import { Effect, Schema, Stream } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient, HttpApiEndpoint, HttpApiGroup, HttpApiSchema } from "effect/unstable/httpapi"
import { ClientError } from "./client-error"

const Endpoint0Success = Schema.String

const Endpoint1Headers = Schema.Struct({
  aUtHoRiZaTiOn: Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])),
  "X-Factory": Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])),
  "x-orchestra-location": Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])),
})

const Endpoint1Success = Schema.String

const Endpoint2Payload0 = Schema.Struct({ message: Schema.String })

const Endpoint2Success = Schema.String

const Endpoint3Payload0 = Schema.Struct({ message: Schema.String })

const Endpoint3Success = Schema.String

const Endpoint4Headers = Schema.Struct({
  authorization: Schema.optionalKey(Schema.Union([Schema.String, Schema.Undefined])),
})

const Endpoint4SuccessData = Schema.Struct({ type: Schema.String })

const Endpoint4SuccessError = Schema.Never

export const Group0 = HttpApiGroup.make("probe", { topLevel: false })
  .add(HttpApiEndpoint.make("GET")("read", "/read", { success: Endpoint0Success }))
  .add(HttpApiEndpoint.make("GET")("override", "/override", { headers: Endpoint1Headers, success: Endpoint1Success }))
  .add(HttpApiEndpoint.make("POST")("json", "/json", { payload: Endpoint2Payload0, success: Endpoint2Success }))
  .add(HttpApiEndpoint.make("POST")("upload", "/upload", { payload: Endpoint3Payload0, success: Endpoint3Success }))
  .add(
    HttpApiEndpoint.make("GET")("events", "/events", {
      headers: Endpoint4Headers,
      success: HttpApiSchema.StreamSse({
        data: Endpoint4SuccessData,
        error: Endpoint4SuccessError,
        contentType: "text/event-stream",
      }),
    }),
  )

type RawGroup = HttpApiClient.Client.Group<typeof Group0, "probe", never, never>

const Endpoint0DeclaredError = Schema.Never
const mapEndpoint0Error = (error: unknown) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : Schema.is(Endpoint0DeclaredError)(error)
      ? error
      : new ClientError({ cause: error })
const Endpoint0 = (raw: RawGroup) => () => raw["read"]({}).pipe(Effect.mapError(mapEndpoint0Error))

type Endpoint1Input = {
  readonly aUtHoRiZaTiOn?: (typeof Endpoint1Headers.Type)["aUtHoRiZaTiOn"]
  readonly "X-Factory"?: (typeof Endpoint1Headers.Type)["X-Factory"]
  readonly "x-orchestra-location"?: (typeof Endpoint1Headers.Type)["x-orchestra-location"]
}
const Endpoint1DeclaredError = Schema.Never
const mapEndpoint1Error = (error: unknown) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : Schema.is(Endpoint1DeclaredError)(error)
      ? error
      : new ClientError({ cause: error })
const Endpoint1 = (raw: RawGroup) => (input?: Endpoint1Input) =>
  raw["override"]({
    headers: {
      aUtHoRiZaTiOn: input?.["aUtHoRiZaTiOn"],
      "X-Factory": input?.["X-Factory"],
      "x-orchestra-location": input?.["x-orchestra-location"],
    },
  }).pipe(Effect.mapError(mapEndpoint1Error))

type Endpoint2Input = { readonly message: (typeof Endpoint2Payload0.Type)["message"] }
const Endpoint2DeclaredError = Schema.Never
const mapEndpoint2Error = (error: unknown) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : Schema.is(Endpoint2DeclaredError)(error)
      ? error
      : new ClientError({ cause: error })
const Endpoint2 = (raw: RawGroup) => (input: Endpoint2Input) =>
  raw["json"]({ payload: { message: input["message"] } }).pipe(Effect.mapError(mapEndpoint2Error))

type Endpoint3Input = { readonly message: (typeof Endpoint3Payload0.Type)["message"] }
const Endpoint3DeclaredError = Schema.Never
const mapEndpoint3Error = (error: unknown) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : Schema.is(Endpoint3DeclaredError)(error)
      ? error
      : new ClientError({ cause: error })
const Endpoint3 = (raw: RawGroup) => (input: Endpoint3Input) =>
  raw["upload"]({ payload: { message: input["message"] } }).pipe(Effect.mapError(mapEndpoint3Error))

type Endpoint4Input = { readonly authorization?: (typeof Endpoint4Headers.Type)["authorization"] }
const Endpoint4DeclaredError = Schema.Union([Endpoint4SuccessError])
const mapEndpoint4Error = (error: unknown) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : Schema.is(Endpoint4DeclaredError)(error)
      ? error
      : new ClientError({ cause: error })
const Endpoint4 = (raw: RawGroup) => (input?: Endpoint4Input) =>
  Stream.unwrap(
    raw["events"]({ headers: { authorization: input?.["authorization"] } }).pipe(
      Effect.mapError(mapEndpoint4Error),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapEndpoint4Error))),
    ),
  )

export const adaptGroup0 = (raw: RawGroup) => ({
  read: Endpoint0(raw),
  override: Endpoint1(raw),
  json: Endpoint2(raw),
  upload: Endpoint3(raw),
  events: Endpoint4(raw),
})
