#!/usr/bin/env bun

import { execFileSync } from "node:child_process"
import { existsSync, readFileSync } from "node:fs"
import { resolve } from "node:path"

export const NORMAL_LIMIT_LOC = 400
export const TOLERANCE_LIMIT_LOC = 600
export const EXCEPTION_LIMIT_LOC = 700

const SOURCE_EXTENSIONS = new Set(["ts", "tsx", "js", "jsx", "mjs", "cjs"])
const IGNORED_SEGMENTS = new Set([".git", "node_modules", "dist", "build", "coverage", ".next", ".sst", ".turbo"])
const EXCLUDED_PREFIXES = ["foundation/atlas/"]

export type Finding = {
  file: string
  lines: number
  baseLines?: number
  kind: "tolerance" | "exception" | "legacy"
  reason?: string
}

export type Report = {
  checked: number
  warnings: Finding[]
  errors: string[]
}

function git(cwd: string, args: string[]) {
  return execFileSync("git", ["-C", cwd, ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] })
}

function sourceFile(file: string) {
  if (EXCLUDED_PREFIXES.some((prefix) => file.startsWith(prefix))) return false
  if (file.split("/").some((segment) => IGNORED_SEGMENTS.has(segment))) return false
  return SOURCE_EXTENSIONS.has(file.split(".").at(-1) ?? "")
}

export function countLoc(text: string) {
  return text.split(/\r\n|\r|\n/).filter((line) => line.trim().length > 0).length
}

function baseFileLoc(cwd: string, base: string, file: string) {
  try {
    git(cwd, ["cat-file", "-e", `${base}:${file}`])
    return countLoc(git(cwd, ["show", `${base}:${file}`]))
  } catch {
    return undefined
  }
}

function mergeBase(cwd: string, baseRef: string) {
  try {
    return git(cwd, ["merge-base", baseRef, "HEAD"]).trim()
  } catch {
    return undefined
  }
}

function resolveBase(cwd: string, baseRef: string) {
  const base = mergeBase(cwd, baseRef)
  if (base) return base
  try {
    return git(cwd, ["rev-parse", "--verify", `${baseRef}^{commit}`]).trim()
  } catch {
    return undefined
  }
}

type Waiver = {
  reason: unknown
  authorizedBy: unknown
  authorizedAt: unknown
}

function waivers(cwd: string): { entries: Record<string, Waiver>; errors: string[] } {
  const file = resolve(cwd, "godfile-waivers.json")
  if (!existsSync(file)) return { entries: {}, errors: [] }
  try {
    const value = JSON.parse(readFileSync(file, "utf8")) as { waivers?: unknown }
    if (
      !value.waivers ||
      typeof value.waivers !== "object" ||
      Array.isArray(value.waivers) ||
      Object.keys(value.waivers).length === 0
    ) {
      return { entries: {}, errors: ["godfile-waivers.json: expected non-empty waivers object"] }
    }
    const entries = value.waivers as Record<string, Waiver>
    const errors = Object.entries(entries).flatMap(([path, entry]) => {
      if (
        !entry ||
        typeof entry.reason !== "string" ||
        !entry.reason.trim() ||
        typeof entry.authorizedBy !== "string" ||
        !entry.authorizedBy.trim() ||
        typeof entry.authorizedAt !== "string" ||
        !entry.authorizedAt.trim()
      ) {
        return [`godfile-waivers.json: invalid waiver for ${path}`]
      }
      return []
    })
    return { entries, errors }
  } catch {
    return { entries: {}, errors: ["godfile-waivers.json: invalid JSON"] }
  }
}

export function runGodfileGate(input: { cwd: string; baseRef: string }): Report {
  const base = resolveBase(input.cwd, input.baseRef)
  if (!base) {
    return {
      checked: 0,
      warnings: [],
      errors: [`Cannot resolve merge-base for ${input.baseRef}. Set GODFILE_BASE_REF to fetched target branch.`],
    }
  }

  const files = git(input.cwd, ["ls-files", "-co", "--exclude-standard", "-z"])
    .split("\0")
    .filter((file) => existsSync(resolve(input.cwd, file)))
    .filter(sourceFile)

  if (files.length === 0) {
    return { checked: 0, warnings: [], errors: ["Godfile gate discovered zero source files; refusing vacuous pass."] }
  }

  const warnings: Finding[] = []
  const errors: string[] = []
  const waiverLedger = waivers(input.cwd)
  errors.push(...waiverLedger.errors)
  const seenWaivers = new Set<string>()

  for (const file of files) {
    const text = readFileSync(resolve(input.cwd, file), "utf8")
    if (text.split(/\r\n|\r|\n/, 1)[0] === "// This file is auto-generated by @hey-api/openapi-ts") continue

    const lines = countLoc(text)
    if (lines <= NORMAL_LIMIT_LOC) continue

    if (lines <= TOLERANCE_LIMIT_LOC) {
      warnings.push({ file, lines, kind: "tolerance" })
      continue
    }

    const baseLines = baseFileLoc(input.cwd, base, file)
    const waiver = waiverLedger.entries[file]
    if (waiver && baseLines !== undefined) seenWaivers.add(file)
    if (lines > EXCEPTION_LIMIT_LOC && baseLines !== undefined && lines <= baseLines) {
      warnings.push({ file, lines, baseLines, kind: "legacy" })
      continue
    }

    if (lines <= EXCEPTION_LIMIT_LOC && waiver && baseLines !== undefined) {
      warnings.push({ file, lines, baseLines, kind: "exception", reason: typeof waiver.reason === "string" ? waiver.reason : undefined })
      continue
    }

    const baseline = baseLines === undefined ? "new file" : `base ${baseLines} LOC`
    if (lines <= EXCEPTION_LIMIT_LOC) {
      errors.push(`${file}: ${lines} LOC requires approved exception (${baseline}).`)
      continue
    }
    errors.push(`${file}: ${lines} LOC exceeds ${EXCEPTION_LIMIT_LOC} (${baseline}). Split file or reduce it.`)
  }

  for (const file of Object.keys(waiverLedger.entries)) {
    if (seenWaivers.has(file)) continue
    errors.push(`godfile-waivers.json: stale waiver for ${file}; reduce/remove it or restore the named legacy file.`)
  }

  return { checked: files.length, warnings, errors }
}

export function formatGodfileReport(report: Report) {
  const lines = [
    `Godfile: ${report.checked} source files, ${report.warnings.length} warnings, ${report.errors.length} errors.`,
  ]

  for (const finding of report.warnings) {
    if (finding.kind === "tolerance")
      lines.push(`WARN ${finding.file}: ${finding.lines} LOC exceeds normal limit ${NORMAL_LIMIT_LOC}.`)
    if (finding.kind === "legacy") {
      lines.push(
        `WARN ${finding.file}: ${finding.lines} LOC exceeds exception limit ${EXCEPTION_LIMIT_LOC}; legacy base ${finding.baseLines} LOC did not grow.`,
      )
    }
    if (finding.kind === "exception") {
      lines.push(
        `WARN ${finding.file}: ${finding.lines} LOC under approved exception; ${finding.reason ?? "no reason"}.`,
      )
    }
  }
  for (const error of report.errors) lines.push(`ERROR ${error}`)
  return lines.join("\n")
}

function parseArgs(args: string[]) {
  const base = args.indexOf("--base")
  if (base === -1) return { baseRef: process.env.GODFILE_BASE_REF ?? "origin/dev" }
  if (!args[base + 1] || args.length !== 2) throw new Error("Usage: bun run script/godfile.ts [--base <git-ref>]")
  return { baseRef: args[base + 1] }
}

if (import.meta.main) {
  const { baseRef } = parseArgs(Bun.argv.slice(2))
  const report = runGodfileGate({ cwd: resolve(import.meta.dir, ".."), baseRef })
  console.log(formatGodfileReport(report))
  if (report.errors.length > 0) process.exitCode = 1
}
