#!/usr/bin/env python3
"""Generate only macOS assets from the immutable, tracked HuGR inverse symbol.

From packages/desktop:
  python3 scripts/mac-icons.py --preview-dir /path/to/temporary/previews
  python3 scripts/mac-icons.py --check

Requires macOS iconutil, rsvg-convert (librsvg), and Pillow. Reference toolchain:
librsvg 2.62.1, Pillow 12.2.0, macOS 15.3.2 iconutil. No downloaded inputs.
The SVG is rasterized unchanged; only transparent margins are cropped. Channels
intentionally match: the existing kit has no dev/beta identity distinction.
Linux/window PNGs and Windows ICOs are never generator outputs.
"""

import argparse
import hashlib
import io
from pathlib import Path
import subprocess
import tempfile

from PIL import Image, ImageDraw, ImageFilter


SOURCE_HASH = "82cff13b0a868deb16ad7fb1b14689a2be3aa39331fd255ecff35ddb626534ca"
SIZES = (16, 32, 64, 128, 256, 512, 1024)
CHANNELS = ("dev", "beta", "prod")


def render(glyph, size):
    # Apple's typical 824 px body on a 1024 px transparent canvas. Work at 4x
    # each target size so the tiny Dock renditions retain antialiased geometry.
    scale = size * 4 / 1024
    canvas = size * 4
    mask = Image.new("L", (canvas, canvas))
    ImageDraw.Draw(mask).rounded_rectangle(
        tuple(round(value * scale) for value in (100, 100, 924, 924)),
        radius=round(185 * scale),
        fill=255,
    )
    shadow_mask = Image.new("L", (canvas, canvas))
    shadow_mask.paste(mask, (0, round(12 * scale)))
    shadow_mask = shadow_mask.filter(ImageFilter.GaussianBlur(12 * scale))
    image = Image.new("RGBA", (canvas, canvas), (0, 0, 0, 0))
    shadow = Image.new("RGBA", image.size, (0, 0, 0, 0))
    shadow.putalpha(shadow_mask.point(lambda value: round(value * 0.24)))
    image.alpha_composite(shadow)
    body = Image.new("RGBA", image.size, (8, 12, 17, 255))
    body.putalpha(mask)
    image.alpha_composite(body)
    # Uniform fit, no recoloring, path changes, or aspect-ratio distortion.
    mark = glyph.copy()
    mark.thumbnail((round(590 * scale), round(590 * scale)), Image.Resampling.LANCZOS)
    image.alpha_composite(mark, ((canvas - mark.width) // 2, (canvas - mark.height) // 2))
    return image.resize((size, size), Image.Resampling.LANCZOS)


def png(image):
    output = io.BytesIO()
    image.save(output, format="PNG", compress_level=9)
    return output.getvalue()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Compare regenerated bytes without updating assets")
    parser.add_argument("--preview-dir", type=Path, help="Save 16–1024 px PNG previews outside the asset folders")
    args = parser.parse_args()
    desktop = Path(__file__).resolve().parents[1]
    source = desktop.parent / "app/public/orchestra/hugr-symbol-inverse.svg"
    if hashlib.sha256(source.read_bytes()).hexdigest() != SOURCE_HASH:
        raise ValueError("Official inverse symbol hash changed; obtain brand approval before regenerating")

    with tempfile.TemporaryDirectory(prefix="orchestra-mac-icons-") as temporary:
        work = Path(temporary)
        subprocess.run(
            ["rsvg-convert", "--width", "2048", "--height", "2048", "--output", str(work / "glyph.png"), str(source)],
            check=True,
        )
        glyph = Image.open(work / "glyph.png").convert("RGBA")
        bounds = glyph.getchannel("A").getbbox()
        if bounds is None:
            raise ValueError("Official symbol rasterized empty")
        glyph = glyph.crop(bounds)
        images = {size: render(glyph, size) for size in SIZES}
        for size, image in images.items():
            if image.size != (size, size) or image.mode != "RGBA":
                raise ValueError(f"Invalid {size} px rendition")
            if any(image.getpixel(corner)[3] != 0 for corner in ((0, 0), (0, size - 1), (size - 1, 0), (size - 1, size - 1))):
                raise ValueError(f"Opaque corner in {size} px rendition")
            if image.getchannel("A").getextrema() != (0, 255):
                raise ValueError(f"Missing transparent padding or opaque body in {size} px rendition")
        renditions = {size: png(image) for size, image in images.items()}
        iconset = work / "Orchestra.iconset"
        iconset.mkdir()
        for size in (16, 32, 128, 256, 512):
            (iconset / f"icon_{size}x{size}.png").write_bytes(renditions[size])
            (iconset / f"icon_{size}x{size}@2x.png").write_bytes(renditions[size * 2])
        # Use Apple's encoder rather than assuming PNG support in legacy ICNS
        # slots. Its 16/32 px codec preserves alpha but may round RGB values.
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(work / "icon.icns")], check=True)
        outputs = {"icon.icns": (work / "icon.icns").read_bytes(), "dock.png": renditions[256]}
        for channel in CHANNELS:
            for name, data in outputs.items():
                target = desktop / "icons" / channel / name
                if args.check:
                    if target.read_bytes() != data:
                        raise ValueError(f"Asset differs from regeneration: {target}")
                if not args.check:
                    target.write_bytes(data)
        if args.preview_dir:
            args.preview_dir.mkdir(parents=True, exist_ok=True)
            for size, data in renditions.items():
                (args.preview_dir / f"orchestra-{size}.png").write_bytes(data)
        print(f"{'Verified' if args.check else 'Generated'} macOS assets for {', '.join(CHANNELS)}")
        print(f"Source SHA-256: {SOURCE_HASH}")
        for name, data in outputs.items():
            print(f"{name} SHA-256: {hashlib.sha256(data).hexdigest()}")


if __name__ == "__main__":
    main()
