// Generated by @orchestra/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClient, HttpClientError, HttpClientRequest } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

type Endpoint1_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint1_0Input = { readonly location?: Endpoint1_0Request["query"]["location"] }
const Endpoint1_0 = (raw: RawClient["server.location"]) => (input?: Endpoint1_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.location"]) => ({ get: Endpoint1_0(raw) })

type Endpoint2_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint2_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint2_1Request = Parameters<RawClient["server.agent"]["agent.file.get"]>[0]
type Endpoint2_1Input = {
  readonly agentID: Endpoint2_1Request["params"]["agentID"]
  readonly location?: Endpoint2_1Request["query"]["location"]
}
const Endpoint2_1 = (raw: RawClient["server.agent"]) => (input: Endpoint2_1Input) =>
  raw["agent.file.get"]({ params: { agentID: input["agentID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint2_2Request = Parameters<RawClient["server.agent"]["agent.file.update"]>[0]
type Endpoint2_2Input = {
  readonly agentID: Endpoint2_2Request["params"]["agentID"]
  readonly location?: Endpoint2_2Request["query"]["location"]
  readonly description?: Endpoint2_2Request["payload"]["description"]
  readonly mode?: Endpoint2_2Request["payload"]["mode"]
  readonly model?: Endpoint2_2Request["payload"]["model"]
  readonly steps?: Endpoint2_2Request["payload"]["steps"]
  readonly system?: Endpoint2_2Request["payload"]["system"]
  readonly permission?: Endpoint2_2Request["payload"]["permission"]
  readonly disable?: Endpoint2_2Request["payload"]["disable"]
  readonly revision?: Endpoint2_2Request["payload"]["revision"]
}
const Endpoint2_2 = (raw: RawClient["server.agent"]) => (input: Endpoint2_2Input) =>
  raw["agent.file.update"]({
    params: { agentID: input["agentID"] },
    query: { location: input["location"] },
    payload: {
      description: input["description"],
      mode: input["mode"],
      model: input["model"],
      steps: input["steps"],
      system: input["system"],
      permission: input["permission"],
      disable: input["disable"],
      revision: input["revision"],
    },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.agent"]) => ({
  list: Endpoint2_0(raw),
  getFile: Endpoint2_1(raw),
  updateFile: Endpoint2_2(raw),
})

type Endpoint3_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint3_0Input = {
  readonly workspace?: Endpoint3_0Request["query"]["workspace"]
  readonly limit?: Endpoint3_0Request["query"]["limit"]
  readonly order?: Endpoint3_0Request["query"]["order"]
  readonly search?: Endpoint3_0Request["query"]["search"]
  readonly directory?: Endpoint3_0Request["query"]["directory"]
  readonly project?: Endpoint3_0Request["query"]["project"]
  readonly subpath?: Endpoint3_0Request["query"]["subpath"]
  readonly cursor?: Endpoint3_0Request["query"]["cursor"]
}
const Endpoint3_0 = (raw: RawClient["server.session"]) => (input?: Endpoint3_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint3_1Input = {
  readonly id?: Endpoint3_1Request["payload"]["id"]
  readonly agent?: Endpoint3_1Request["payload"]["agent"]
  readonly model?: Endpoint3_1Request["payload"]["model"]
  readonly location?: Endpoint3_1Request["payload"]["location"]
}
const Endpoint3_1 = (raw: RawClient["server.session"]) => (input?: Endpoint3_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint3_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint3_3Input = { readonly sessionID: Endpoint3_3Request["params"]["sessionID"] }
const Endpoint3_3 = (raw: RawClient["server.session"]) => (input: Endpoint3_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_4Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint3_4Input = {
  readonly sessionID: Endpoint3_4Request["params"]["sessionID"]
  readonly agent: Endpoint3_4Request["payload"]["agent"]
}
const Endpoint3_4 = (raw: RawClient["server.session"]) => (input: Endpoint3_4Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_5Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint3_5Input = {
  readonly sessionID: Endpoint3_5Request["params"]["sessionID"]
  readonly model: Endpoint3_5Request["payload"]["model"]
}
const Endpoint3_5 = (raw: RawClient["server.session"]) => (input: Endpoint3_5Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint3_6Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint3_6Input = {
  readonly sessionID: Endpoint3_6Request["params"]["sessionID"]
  readonly id?: Endpoint3_6Request["payload"]["id"]
  readonly prompt: Endpoint3_6Request["payload"]["prompt"]
  readonly delivery?: Endpoint3_6Request["payload"]["delivery"]
  readonly resume?: Endpoint3_6Request["payload"]["resume"]
}
const Endpoint3_6 = (raw: RawClient["server.session"]) => (input: Endpoint3_6Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], prompt: input["prompt"], delivery: input["delivery"], resume: input["resume"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_7Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint3_7Input = { readonly sessionID: Endpoint3_7Request["params"]["sessionID"] }
const Endpoint3_7 = (raw: RawClient["server.session"]) => (input: Endpoint3_7Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_8Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint3_8Input = { readonly sessionID: Endpoint3_8Request["params"]["sessionID"] }
const Endpoint3_8 = (raw: RawClient["server.session"]) => (input: Endpoint3_8Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_9Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint3_9Input = {
  readonly sessionID: Endpoint3_9Request["params"]["sessionID"]
  readonly messageID: Endpoint3_9Request["payload"]["messageID"]
  readonly files?: Endpoint3_9Request["payload"]["files"]
}
const Endpoint3_9 = (raw: RawClient["server.session"]) => (input: Endpoint3_9Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_10Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint3_10Input = { readonly sessionID: Endpoint3_10Request["params"]["sessionID"] }
const Endpoint3_10 = (raw: RawClient["server.session"]) => (input: Endpoint3_10Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_11Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint3_11Input = { readonly sessionID: Endpoint3_11Request["params"]["sessionID"] }
const Endpoint3_11 = (raw: RawClient["server.session"]) => (input: Endpoint3_11Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_12Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint3_12Input = { readonly sessionID: Endpoint3_12Request["params"]["sessionID"] }
const Endpoint3_12 = (raw: RawClient["server.session"]) => (input: Endpoint3_12Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint3_13Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint3_13Input = {
  readonly sessionID: Endpoint3_13Request["params"]["sessionID"]
  readonly limit?: Endpoint3_13Request["query"]["limit"]
  readonly after?: Endpoint3_13Request["query"]["after"]
}
const Endpoint3_13 = (raw: RawClient["server.session"]) => (input: Endpoint3_13Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint3_14Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint3_14Input = {
  readonly sessionID: Endpoint3_14Request["params"]["sessionID"]
  readonly after?: Endpoint3_14Request["query"]["after"]
}
const Endpoint3_14 = (raw: RawClient["server.session"]) => (input: Endpoint3_14Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint3_15Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint3_15Input = { readonly sessionID: Endpoint3_15Request["params"]["sessionID"] }
const Endpoint3_15 = (raw: RawClient["server.session"]) => (input: Endpoint3_15Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint3_16Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint3_16Input = {
  readonly sessionID: Endpoint3_16Request["params"]["sessionID"]
  readonly messageID: Endpoint3_16Request["params"]["messageID"]
}
const Endpoint3_16 = (raw: RawClient["server.session"]) => (input: Endpoint3_16Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup3 = (raw: RawClient["server.session"]) => ({
  list: Endpoint3_0(raw),
  create: Endpoint3_1(raw),
  active: Endpoint3_2(raw),
  get: Endpoint3_3(raw),
  switchAgent: Endpoint3_4(raw),
  switchModel: Endpoint3_5(raw),
  prompt: Endpoint3_6(raw),
  compact: Endpoint3_7(raw),
  wait: Endpoint3_8(raw),
  stage: Endpoint3_9(raw),
  clear: Endpoint3_10(raw),
  commit: Endpoint3_11(raw),
  context: Endpoint3_12(raw),
  history: Endpoint3_13(raw),
  events: Endpoint3_14(raw),
  interrupt: Endpoint3_15(raw),
  message: Endpoint3_16(raw),
})

type Endpoint4_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint4_0Input = {
  readonly sessionID: Endpoint4_0Request["params"]["sessionID"]
  readonly limit?: Endpoint4_0Request["query"]["limit"]
  readonly order?: Endpoint4_0Request["query"]["order"]
  readonly cursor?: Endpoint4_0Request["query"]["cursor"]
}
const Endpoint4_0 = (raw: RawClient["server.message"]) => (input: Endpoint4_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup4 = (raw: RawClient["server.message"]) => ({ list: Endpoint4_0(raw) })

type Endpoint5_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint5_0Input = { readonly location?: Endpoint5_0Request["query"]["location"] }
const Endpoint5_0 = (raw: RawClient["server.model"]) => (input?: Endpoint5_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.model"]) => ({ list: Endpoint5_0(raw) })

type Endpoint6_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint6_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint6_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint6_1Input = {
  readonly providerID: Endpoint6_1Request["params"]["providerID"]
  readonly location?: Endpoint6_1Request["query"]["location"]
}
const Endpoint6_1 = (raw: RawClient["server.provider"]) => (input: Endpoint6_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup6 = (raw: RawClient["server.provider"]) => ({ list: Endpoint6_0(raw), get: Endpoint6_1(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint7_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint7_1Input = {
  readonly integrationID: Endpoint7_1Request["params"]["integrationID"]
  readonly location?: Endpoint7_1Request["query"]["location"]
}
const Endpoint7_1 = (raw: RawClient["server.integration"]) => (input: Endpoint7_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint7_2Input = {
  readonly integrationID: Endpoint7_2Request["params"]["integrationID"]
  readonly location?: Endpoint7_2Request["query"]["location"]
  readonly key: Endpoint7_2Request["payload"]["key"]
  readonly label?: Endpoint7_2Request["payload"]["label"]
}
const Endpoint7_2 = (raw: RawClient["server.integration"]) => (input: Endpoint7_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint7_3Input = {
  readonly integrationID: Endpoint7_3Request["params"]["integrationID"]
  readonly location?: Endpoint7_3Request["query"]["location"]
  readonly methodID: Endpoint7_3Request["payload"]["methodID"]
  readonly inputs: Endpoint7_3Request["payload"]["inputs"]
  readonly label?: Endpoint7_3Request["payload"]["label"]
}
const Endpoint7_3 = (raw: RawClient["server.integration"]) => (input: Endpoint7_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint7_4Input = {
  readonly attemptID: Endpoint7_4Request["params"]["attemptID"]
  readonly location?: Endpoint7_4Request["query"]["location"]
}
const Endpoint7_4 = (raw: RawClient["server.integration"]) => (input: Endpoint7_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint7_5Input = {
  readonly attemptID: Endpoint7_5Request["params"]["attemptID"]
  readonly location?: Endpoint7_5Request["query"]["location"]
  readonly code?: Endpoint7_5Request["payload"]["code"]
}
const Endpoint7_5 = (raw: RawClient["server.integration"]) => (input: Endpoint7_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint7_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint7_6Input = {
  readonly attemptID: Endpoint7_6Request["params"]["attemptID"]
  readonly location?: Endpoint7_6Request["query"]["location"]
}
const Endpoint7_6 = (raw: RawClient["server.integration"]) => (input: Endpoint7_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup7 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint7_0(raw),
  get: Endpoint7_1(raw),
  connectKey: Endpoint7_2(raw),
  connectOauth: Endpoint7_3(raw),
  attemptStatus: Endpoint7_4(raw),
  attemptComplete: Endpoint7_5(raw),
  attemptCancel: Endpoint7_6(raw),
})

type Endpoint8_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint8_0Input = {
  readonly credentialID: Endpoint8_0Request["params"]["credentialID"]
  readonly location?: Endpoint8_0Request["query"]["location"]
  readonly label: Endpoint8_0Request["payload"]["label"]
}
const Endpoint8_0 = (raw: RawClient["server.credential"]) => (input: Endpoint8_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint8_1Input = {
  readonly credentialID: Endpoint8_1Request["params"]["credentialID"]
  readonly location?: Endpoint8_1Request["query"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.credential"]) => (input: Endpoint8_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.credential"]) => ({ update: Endpoint8_0(raw), remove: Endpoint8_1(raw) })

type Endpoint9_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint9_0Input = { readonly location?: Endpoint9_0Request["query"]["location"] }
const Endpoint9_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint9_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint9_1Input = { readonly projectID?: Endpoint9_1Request["query"]["projectID"] }
const Endpoint9_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint9_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint9_2Input = { readonly id: Endpoint9_2Request["params"]["id"] }
const Endpoint9_2 = (raw: RawClient["server.permission"]) => (input: Endpoint9_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint9_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint9_3Input = {
  readonly sessionID: Endpoint9_3Request["params"]["sessionID"]
  readonly id?: Endpoint9_3Request["payload"]["id"]
  readonly action: Endpoint9_3Request["payload"]["action"]
  readonly resources: Endpoint9_3Request["payload"]["resources"]
  readonly save?: Endpoint9_3Request["payload"]["save"]
  readonly metadata?: Endpoint9_3Request["payload"]["metadata"]
  readonly source?: Endpoint9_3Request["payload"]["source"]
  readonly agent?: Endpoint9_3Request["payload"]["agent"]
}
const Endpoint9_3 = (raw: RawClient["server.permission"]) => (input: Endpoint9_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint9_4Input = { readonly sessionID: Endpoint9_4Request["params"]["sessionID"] }
const Endpoint9_4 = (raw: RawClient["server.permission"]) => (input: Endpoint9_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint9_5Input = {
  readonly sessionID: Endpoint9_5Request["params"]["sessionID"]
  readonly requestID: Endpoint9_5Request["params"]["requestID"]
}
const Endpoint9_5 = (raw: RawClient["server.permission"]) => (input: Endpoint9_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint9_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint9_6Input = {
  readonly sessionID: Endpoint9_6Request["params"]["sessionID"]
  readonly requestID: Endpoint9_6Request["params"]["requestID"]
  readonly reply: Endpoint9_6Request["payload"]["reply"]
  readonly message?: Endpoint9_6Request["payload"]["message"]
}
const Endpoint9_6 = (raw: RawClient["server.permission"]) => (input: Endpoint9_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint9_0(raw),
  listSaved: Endpoint9_1(raw),
  removeSaved: Endpoint9_2(raw),
  create: Endpoint9_3(raw),
  list: Endpoint9_4(raw),
  get: Endpoint9_5(raw),
  reply: Endpoint9_6(raw),
})

type Endpoint10_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint10_0Input = {
  readonly location?: Endpoint10_0Request["query"]["location"]
  readonly path?: Endpoint10_0Request["query"]["path"]
}
const Endpoint10_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint10_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint10_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint10_1Input = {
  readonly location?: Endpoint10_1Request["query"]["location"]
  readonly query: Endpoint10_1Request["query"]["query"]
  readonly type?: Endpoint10_1Request["query"]["type"]
  readonly limit?: Endpoint10_1Request["query"]["limit"]
}
const Endpoint10_1 = (raw: RawClient["server.fs"]) => (input: Endpoint10_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.fs"]) => ({ list: Endpoint10_0(raw), find: Endpoint10_1(raw) })

type Endpoint11_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint11_0Input = { readonly location?: Endpoint11_0Request["query"]["location"] }
const Endpoint11_0 = (raw: RawClient["server.command"]) => (input?: Endpoint11_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.command"]) => ({ list: Endpoint11_0(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint12_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint12_1Request = Parameters<RawClient["server.skill"]["skill.save"]>[0]
type Endpoint12_1Input = {
  readonly location?: Endpoint12_1Request["query"]["location"]
  readonly name: Endpoint12_1Request["payload"]["name"]
  readonly description: Endpoint12_1Request["payload"]["description"]
  readonly content: Endpoint12_1Request["payload"]["content"]
  readonly path?: Endpoint12_1Request["payload"]["path"]
  readonly mtime?: Endpoint12_1Request["payload"]["mtime"]
}
const Endpoint12_1 = (raw: RawClient["server.skill"]) => (input: Endpoint12_1Input) =>
  raw["skill.save"]({
    query: { location: input["location"] },
    payload: {
      name: input["name"],
      description: input["description"],
      content: input["content"],
      path: input["path"],
      mtime: input["mtime"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint12_2Request = Parameters<RawClient["server.skill"]["skill.remove"]>[0]
type Endpoint12_2Input = {
  readonly location?: Endpoint12_2Request["query"]["location"]
  readonly path: Endpoint12_2Request["query"]["path"]
}
const Endpoint12_2 = (raw: RawClient["server.skill"]) => (input: Endpoint12_2Input) =>
  raw["skill.remove"]({ query: { location: input["location"], path: input["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup12 = (raw: RawClient["server.skill"]) => ({
  list: Endpoint12_0(raw),
  save: Endpoint12_1(raw),
  remove: Endpoint12_2(raw),
})

type Endpoint13_0Request = Parameters<RawClient["server.behavior"]["behavior.set"]>[0]
type Endpoint13_0Input = {
  readonly location?: Endpoint13_0Request["query"]["location"]
  readonly behaviors: Endpoint13_0Request["payload"]["behaviors"]
}
const Endpoint13_0 = (raw: RawClient["server.behavior"]) => (input: Endpoint13_0Input) =>
  raw["behavior.set"]({ query: { location: input["location"] }, payload: { behaviors: input["behaviors"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup13 = (raw: RawClient["server.behavior"]) => ({ set: Endpoint13_0(raw) })

const Endpoint14_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup14 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint14_0(raw) })

type Endpoint15_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
const Endpoint15_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint15_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint15_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint15_1Input = {
  readonly location?: Endpoint15_1Request["query"]["location"]
  readonly command?: Endpoint15_1Request["payload"]["command"]
  readonly args?: Endpoint15_1Request["payload"]["args"]
  readonly cwd?: Endpoint15_1Request["payload"]["cwd"]
  readonly title?: Endpoint15_1Request["payload"]["title"]
  readonly env?: Endpoint15_1Request["payload"]["env"]
}
const Endpoint15_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint15_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint15_2Input = {
  readonly ptyID: Endpoint15_2Request["params"]["ptyID"]
  readonly location?: Endpoint15_2Request["query"]["location"]
}
const Endpoint15_2 = (raw: RawClient["server.pty"]) => (input: Endpoint15_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint15_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint15_3Input = {
  readonly ptyID: Endpoint15_3Request["params"]["ptyID"]
  readonly location?: Endpoint15_3Request["query"]["location"]
  readonly title?: Endpoint15_3Request["payload"]["title"]
  readonly size?: Endpoint15_3Request["payload"]["size"]
}
const Endpoint15_3 = (raw: RawClient["server.pty"]) => (input: Endpoint15_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint15_4Input = {
  readonly ptyID: Endpoint15_4Request["params"]["ptyID"]
  readonly location?: Endpoint15_4Request["query"]["location"]
}
const Endpoint15_4 = (raw: RawClient["server.pty"]) => (input: Endpoint15_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup15 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint15_0(raw),
  create: Endpoint15_1(raw),
  get: Endpoint15_2(raw),
  update: Endpoint15_3(raw),
  remove: Endpoint15_4(raw),
})

type Endpoint16_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
const Endpoint16_0 = (raw: RawClient["server.question"]) => (input?: Endpoint16_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint16_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint16_1Input = { readonly sessionID: Endpoint16_1Request["params"]["sessionID"] }
const Endpoint16_1 = (raw: RawClient["server.question"]) => (input: Endpoint16_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint16_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint16_2Input = {
  readonly sessionID: Endpoint16_2Request["params"]["sessionID"]
  readonly requestID: Endpoint16_2Request["params"]["requestID"]
  readonly answers: Endpoint16_2Request["payload"]["answers"]
}
const Endpoint16_2 = (raw: RawClient["server.question"]) => (input: Endpoint16_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint16_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint16_3Input = {
  readonly sessionID: Endpoint16_3Request["params"]["sessionID"]
  readonly requestID: Endpoint16_3Request["params"]["requestID"]
}
const Endpoint16_3 = (raw: RawClient["server.question"]) => (input: Endpoint16_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup16 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint16_0(raw),
  list: Endpoint16_1(raw),
  reply: Endpoint16_2(raw),
  reject: Endpoint16_3(raw),
})

type Endpoint17_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint17_0Input = { readonly location?: Endpoint17_0Request["query"]["location"] }
const Endpoint17_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint17_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup17 = (raw: RawClient["server.reference"]) => ({ list: Endpoint17_0(raw) })

type Endpoint18_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint18_0Input = {
  readonly projectID: Endpoint18_0Request["params"]["projectID"]
  readonly location?: Endpoint18_0Request["query"]["location"]
  readonly strategy: Endpoint18_0Request["payload"]["strategy"]
  readonly directory: Endpoint18_0Request["payload"]["directory"]
  readonly name?: Endpoint18_0Request["payload"]["name"]
}
const Endpoint18_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint18_1Input = {
  readonly projectID: Endpoint18_1Request["params"]["projectID"]
  readonly location?: Endpoint18_1Request["query"]["location"]
  readonly directory: Endpoint18_1Request["payload"]["directory"]
  readonly force: Endpoint18_1Request["payload"]["force"]
}
const Endpoint18_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint18_2Input = {
  readonly projectID: Endpoint18_2Request["params"]["projectID"]
  readonly location?: Endpoint18_2Request["query"]["location"]
}
const Endpoint18_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup18 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint18_0(raw),
  remove: Endpoint18_1(raw),
  refresh: Endpoint18_2(raw),
})

type Endpoint19_0Request = Parameters<RawClient["server.relay.document"]["relay.document.list"]>[0]
type Endpoint19_0Input = { readonly location?: Endpoint19_0Request["query"]["location"] }
const Endpoint19_0 = (raw: RawClient["server.relay.document"]) => (input?: Endpoint19_0Input) =>
  raw["relay.document.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_1Request = Parameters<RawClient["server.relay.document"]["relay.document.create"]>[0]
type Endpoint19_1Input = {
  readonly location?: Endpoint19_1Request["query"]["location"]
  readonly name?: Endpoint19_1Request["payload"]["name"]
  readonly description?: Endpoint19_1Request["payload"]["description"]
  readonly nodes?: Endpoint19_1Request["payload"]["nodes"]
  readonly connections?: Endpoint19_1Request["payload"]["connections"]
  readonly nodeGroups?: Endpoint19_1Request["payload"]["nodeGroups"]
  readonly tags?: Endpoint19_1Request["payload"]["tags"]
  readonly meta?: Endpoint19_1Request["payload"]["meta"]
  readonly isArchived?: Endpoint19_1Request["payload"]["isArchived"]
}
const Endpoint19_1 = (raw: RawClient["server.relay.document"]) => (input?: Endpoint19_1Input) =>
  raw["relay.document.create"]({
    query: { location: input?.["location"] },
    payload: {
      name: input?.["name"],
      description: input?.["description"],
      nodes: input?.["nodes"],
      connections: input?.["connections"],
      nodeGroups: input?.["nodeGroups"],
      tags: input?.["tags"],
      meta: input?.["meta"],
      isArchived: input?.["isArchived"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_2Request = Parameters<RawClient["server.relay.document"]["relay.document.get"]>[0]
type Endpoint19_2Input = {
  readonly documentID: Endpoint19_2Request["params"]["documentID"]
  readonly location?: Endpoint19_2Request["query"]["location"]
}
const Endpoint19_2 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_2Input) =>
  raw["relay.document.get"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_3Request = Parameters<RawClient["server.relay.document"]["relay.document.update"]>[0]
type Endpoint19_3Input = {
  readonly documentID: Endpoint19_3Request["params"]["documentID"]
  readonly location?: Endpoint19_3Request["query"]["location"]
  readonly name?: Endpoint19_3Request["payload"]["name"]
  readonly description?: Endpoint19_3Request["payload"]["description"]
  readonly nodes?: Endpoint19_3Request["payload"]["nodes"]
  readonly connections?: Endpoint19_3Request["payload"]["connections"]
  readonly nodeGroups?: Endpoint19_3Request["payload"]["nodeGroups"]
  readonly tags?: Endpoint19_3Request["payload"]["tags"]
  readonly meta?: Endpoint19_3Request["payload"]["meta"]
  readonly isArchived?: Endpoint19_3Request["payload"]["isArchived"]
  readonly versionId?: Endpoint19_3Request["payload"]["versionId"]
  readonly expectedChecksum?: Endpoint19_3Request["payload"]["expectedChecksum"]
  readonly force?: Endpoint19_3Request["payload"]["force"]
}
const Endpoint19_3 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_3Input) =>
  raw["relay.document.update"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
    payload: {
      name: input["name"],
      description: input["description"],
      nodes: input["nodes"],
      connections: input["connections"],
      nodeGroups: input["nodeGroups"],
      tags: input["tags"],
      meta: input["meta"],
      isArchived: input["isArchived"],
      versionId: input["versionId"],
      expectedChecksum: input["expectedChecksum"],
      force: input["force"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_4Request = Parameters<RawClient["server.relay.document"]["relay.document.remove"]>[0]
type Endpoint19_4Input = {
  readonly documentID: Endpoint19_4Request["params"]["documentID"]
  readonly location?: Endpoint19_4Request["query"]["location"]
}
const Endpoint19_4 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_4Input) =>
  raw["relay.document.remove"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_5Request = Parameters<RawClient["server.relay.document"]["relay.document.versions"]>[0]
type Endpoint19_5Input = {
  readonly documentID: Endpoint19_5Request["params"]["documentID"]
  readonly location?: Endpoint19_5Request["query"]["location"]
}
const Endpoint19_5 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_5Input) =>
  raw["relay.document.versions"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_6Request = Parameters<RawClient["server.relay.document"]["relay.document.version"]>[0]
type Endpoint19_6Input = {
  readonly documentID: Endpoint19_6Request["params"]["documentID"]
  readonly versionID: Endpoint19_6Request["params"]["versionID"]
  readonly location?: Endpoint19_6Request["query"]["location"]
}
const Endpoint19_6 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_6Input) =>
  raw["relay.document.version"]({
    params: { documentID: input["documentID"], versionID: input["versionID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_7Request = Parameters<RawClient["server.relay.document"]["relay.document.sprint"]>[0]
type Endpoint19_7Input = {
  readonly documentID: Endpoint19_7Request["params"]["documentID"]
  readonly location?: Endpoint19_7Request["query"]["location"]
}
const Endpoint19_7 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_7Input) =>
  raw["relay.document.sprint"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_8Request = Parameters<RawClient["server.relay.document"]["relay.document.export"]>[0]
type Endpoint19_8Input = {
  readonly documentID: Endpoint19_8Request["params"]["documentID"]
  readonly location?: Endpoint19_8Request["query"]["location"]
}
const Endpoint19_8 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_8Input) =>
  raw["relay.document.export"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_9Request = Parameters<RawClient["server.relay.document"]["relay.document.check"]>[0]
type Endpoint19_9Input = {
  readonly documentID: Endpoint19_9Request["params"]["documentID"]
  readonly location?: Endpoint19_9Request["query"]["location"]
  readonly position?: Endpoint19_9Request["payload"]["position"]
  readonly counter?: Endpoint19_9Request["payload"]["counter"]
  readonly baseRef?: Endpoint19_9Request["payload"]["baseRef"]
  readonly params?: Endpoint19_9Request["payload"]["params"]
}
const Endpoint19_9 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_9Input) =>
  raw["relay.document.check"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
    payload: {
      position: input["position"],
      counter: input["counter"],
      baseRef: input["baseRef"],
      params: input["params"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_10Request = Parameters<RawClient["server.relay.document"]["relay.document.nodeTypes"]>[0]
type Endpoint19_10Input = { readonly location?: Endpoint19_10Request["query"]["location"] }
const Endpoint19_10 = (raw: RawClient["server.relay.document"]) => (input?: Endpoint19_10Input) =>
  raw["relay.document.nodeTypes"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_11Request = Parameters<RawClient["server.relay.document"]["relay.scope.list"]>[0]
type Endpoint19_11Input = { readonly location?: Endpoint19_11Request["query"]["location"] }
const Endpoint19_11 = (raw: RawClient["server.relay.document"]) => (input?: Endpoint19_11Input) =>
  raw["relay.scope.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint19_12Request = Parameters<RawClient["server.relay.document"]["relay.scope.create"]>[0]
type Endpoint19_12Input = {
  readonly location?: Endpoint19_12Request["query"]["location"]
  readonly name: Endpoint19_12Request["payload"]["name"]
  readonly description?: Endpoint19_12Request["payload"]["description"]
}
const Endpoint19_12 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_12Input) =>
  raw["relay.scope.create"]({
    query: { location: input["location"] },
    payload: { name: input["name"], description: input["description"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_13Request = Parameters<RawClient["server.relay.document"]["relay.scope.update"]>[0]
type Endpoint19_13Input = {
  readonly scopeID: Endpoint19_13Request["params"]["scopeID"]
  readonly location?: Endpoint19_13Request["query"]["location"]
  readonly name: Endpoint19_13Request["payload"]["name"]
  readonly description?: Endpoint19_13Request["payload"]["description"]
}
const Endpoint19_13 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_13Input) =>
  raw["relay.scope.update"]({
    params: { scopeID: input["scopeID"] },
    query: { location: input["location"] },
    payload: { name: input["name"], description: input["description"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint19_14Request = Parameters<RawClient["server.relay.document"]["relay.scope.remove"]>[0]
type Endpoint19_14Input = {
  readonly scopeID: Endpoint19_14Request["params"]["scopeID"]
  readonly location?: Endpoint19_14Request["query"]["location"]
}
const Endpoint19_14 = (raw: RawClient["server.relay.document"]) => (input: Endpoint19_14Input) =>
  raw["relay.scope.remove"]({ params: { scopeID: input["scopeID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup19 = (raw: RawClient["server.relay.document"]) => ({
  list: Endpoint19_0(raw),
  create: Endpoint19_1(raw),
  get: Endpoint19_2(raw),
  update: Endpoint19_3(raw),
  remove: Endpoint19_4(raw),
  versions: Endpoint19_5(raw),
  version: Endpoint19_6(raw),
  sprint: Endpoint19_7(raw),
  definition: Endpoint19_8(raw),
  check: Endpoint19_9(raw),
  nodeTypes: Endpoint19_10(raw),
  listScopes: Endpoint19_11(raw),
  createScope: Endpoint19_12(raw),
  updateScope: Endpoint19_13(raw),
  removeScope: Endpoint19_14(raw),
})

type Endpoint20_0Request = Parameters<RawClient["server.relay.publish"]["relay.publish.publish"]>[0]
type Endpoint20_0Input = {
  readonly documentID: Endpoint20_0Request["params"]["documentID"]
  readonly location?: Endpoint20_0Request["query"]["location"]
  readonly versionId: Endpoint20_0Request["payload"]["versionId"]
  readonly expectedChecksum?: Endpoint20_0Request["payload"]["expectedChecksum"]
}
const Endpoint20_0 = (raw: RawClient["server.relay.publish"]) => (input: Endpoint20_0Input) =>
  raw["relay.publish.publish"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
    payload: { versionId: input["versionId"], expectedChecksum: input["expectedChecksum"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint20_1Request = Parameters<RawClient["server.relay.publish"]["relay.publish.unpublish"]>[0]
type Endpoint20_1Input = {
  readonly documentID: Endpoint20_1Request["params"]["documentID"]
  readonly location?: Endpoint20_1Request["query"]["location"]
  readonly expectedChecksum?: Endpoint20_1Request["payload"]["expectedChecksum"]
}
const Endpoint20_1 = (raw: RawClient["server.relay.publish"]) => (input: Endpoint20_1Input) =>
  raw["relay.publish.unpublish"]({
    params: { documentID: input["documentID"] },
    query: { location: input["location"] },
    payload: { expectedChecksum: input["expectedChecksum"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup20 = (raw: RawClient["server.relay.publish"]) => ({
  publish: Endpoint20_0(raw),
  unpublish: Endpoint20_1(raw),
})

type Endpoint21_0Request = Parameters<RawClient["server.relay.hook"]["relay.hook.list"]>[0]
type Endpoint21_0Input = { readonly location?: Endpoint21_0Request["query"]["location"] }
const Endpoint21_0 = (raw: RawClient["server.relay.hook"]) => (input?: Endpoint21_0Input) =>
  raw["relay.hook.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint21_1Request = Parameters<RawClient["server.relay.hook"]["relay.hook.install"]>[0]
type Endpoint21_1Input = {
  readonly location?: Endpoint21_1Request["query"]["location"]
  readonly document: Endpoint21_1Request["payload"]["document"]
  readonly version?: Endpoint21_1Request["payload"]["version"]
}
const Endpoint21_1 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_1Input) =>
  raw["relay.hook.install"]({
    query: { location: input["location"] },
    payload: { document: input["document"], version: input["version"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_2Request = Parameters<RawClient["server.relay.hook"]["relay.hook.update"]>[0]
type Endpoint21_2Input = {
  readonly installID: Endpoint21_2Request["params"]["installID"]
  readonly location?: Endpoint21_2Request["query"]["location"]
  readonly version?: Endpoint21_2Request["payload"]["version"]
}
const Endpoint21_2 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_2Input) =>
  raw["relay.hook.update"]({
    params: { installID: input["installID"] },
    query: { location: input["location"] },
    payload: { version: input["version"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_3Request = Parameters<RawClient["server.relay.hook"]["relay.hook.enable"]>[0]
type Endpoint21_3Input = {
  readonly installID: Endpoint21_3Request["params"]["installID"]
  readonly location?: Endpoint21_3Request["query"]["location"]
}
const Endpoint21_3 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_3Input) =>
  raw["relay.hook.enable"]({ params: { installID: input["installID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint21_4Request = Parameters<RawClient["server.relay.hook"]["relay.hook.disable"]>[0]
type Endpoint21_4Input = {
  readonly installID: Endpoint21_4Request["params"]["installID"]
  readonly location?: Endpoint21_4Request["query"]["location"]
}
const Endpoint21_4 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_4Input) =>
  raw["relay.hook.disable"]({ params: { installID: input["installID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint21_5Request = Parameters<RawClient["server.relay.hook"]["relay.hook.order"]>[0]
type Endpoint21_5Input = {
  readonly location?: Endpoint21_5Request["query"]["location"]
  readonly installIDs: Endpoint21_5Request["payload"]["installIDs"]
}
const Endpoint21_5 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_5Input) =>
  raw["relay.hook.order"]({
    query: { location: input["location"] },
    payload: { installIDs: input["installIDs"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_6Request = Parameters<RawClient["server.relay.hook"]["relay.hook.uninstall"]>[0]
type Endpoint21_6Input = {
  readonly installID: Endpoint21_6Request["params"]["installID"]
  readonly location?: Endpoint21_6Request["query"]["location"]
}
const Endpoint21_6 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_6Input) =>
  raw["relay.hook.uninstall"]({
    params: { installID: input["installID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_7Request = Parameters<RawClient["server.relay.hook"]["relay.hook.decisions"]>[0]
type Endpoint21_7Input = {
  readonly installID: Endpoint21_7Request["params"]["installID"]
  readonly location?: Endpoint21_7Request["query"]["location"]
}
const Endpoint21_7 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_7Input) =>
  raw["relay.hook.decisions"]({
    params: { installID: input["installID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint21_8Request = Parameters<RawClient["server.relay.hook"]["relay.hook.repair"]>[0]
type Endpoint21_8Input = {
  readonly location?: Endpoint21_8Request["query"]["location"]
  readonly confirm: Endpoint21_8Request["payload"]["confirm"]
}
const Endpoint21_8 = (raw: RawClient["server.relay.hook"]) => (input: Endpoint21_8Input) =>
  raw["relay.hook.repair"]({ query: { location: input["location"] }, payload: { confirm: input["confirm"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup21 = (raw: RawClient["server.relay.hook"]) => ({
  list: Endpoint21_0(raw),
  install: Endpoint21_1(raw),
  update: Endpoint21_2(raw),
  enable: Endpoint21_3(raw),
  disable: Endpoint21_4(raw),
  order: Endpoint21_5(raw),
  uninstall: Endpoint21_6(raw),
  decisions: Endpoint21_7(raw),
  repair: Endpoint21_8(raw),
})

type Endpoint22_0Request = Parameters<RawClient["server.pullRequest"]["pullRequest.list"]>[0]
type Endpoint22_0Input = { readonly location?: Endpoint22_0Request["query"]["location"] }
const Endpoint22_0 = (raw: RawClient["server.pullRequest"]) => (input?: Endpoint22_0Input) =>
  raw["pullRequest.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint22_1Request = Parameters<RawClient["server.pullRequest"]["pullRequest.create"]>[0]
type Endpoint22_1Input = {
  readonly location?: Endpoint22_1Request["query"]["location"]
  readonly title: Endpoint22_1Request["payload"]["title"]
  readonly body: Endpoint22_1Request["payload"]["body"]
  readonly base: Endpoint22_1Request["payload"]["base"]
  readonly head?: Endpoint22_1Request["payload"]["head"]
}
const Endpoint22_1 = (raw: RawClient["server.pullRequest"]) => (input: Endpoint22_1Input) =>
  raw["pullRequest.create"]({
    query: { location: input["location"] },
    payload: { title: input["title"], body: input["body"], base: input["base"], head: input["head"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup22 = (raw: RawClient["server.pullRequest"]) => ({ list: Endpoint22_0(raw), create: Endpoint22_1(raw) })

type Endpoint23_0Request = Parameters<RawClient["server.schedule"]["schedule.list"]>[0]
type Endpoint23_0Input = { readonly location?: Endpoint23_0Request["query"]["location"] }
const Endpoint23_0 = (raw: RawClient["server.schedule"]) => (input?: Endpoint23_0Input) =>
  raw["schedule.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint23_1Request = Parameters<RawClient["server.schedule"]["schedule.create"]>[0]
type Endpoint23_1Input = {
  readonly location?: Endpoint23_1Request["query"]["location"]
  readonly id?: Endpoint23_1Request["payload"]["id"]
  readonly name: Endpoint23_1Request["payload"]["name"]
  readonly prompt: Endpoint23_1Request["payload"]["prompt"]
  readonly cadence: Endpoint23_1Request["payload"]["cadence"]
  readonly next: Endpoint23_1Request["payload"]["next"]
  readonly timezone: Endpoint23_1Request["payload"]["timezone"]
  readonly minute?: Endpoint23_1Request["payload"]["minute"]
  readonly enabled?: Endpoint23_1Request["payload"]["enabled"]
  readonly history?: Endpoint23_1Request["payload"]["history"]
}
const Endpoint23_1 = (raw: RawClient["server.schedule"]) => (input: Endpoint23_1Input) =>
  raw["schedule.create"]({
    query: { location: input["location"] },
    payload: {
      id: input["id"],
      name: input["name"],
      prompt: input["prompt"],
      cadence: input["cadence"],
      next: input["next"],
      timezone: input["timezone"],
      minute: input["minute"],
      enabled: input["enabled"],
      history: input["history"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_2Request = Parameters<RawClient["server.schedule"]["schedule.update"]>[0]
type Endpoint23_2Input = {
  readonly scheduleID: Endpoint23_2Request["params"]["scheduleID"]
  readonly location?: Endpoint23_2Request["query"]["location"]
  readonly name?: Endpoint23_2Request["payload"]["name"]
  readonly prompt?: Endpoint23_2Request["payload"]["prompt"]
  readonly cadence?: Endpoint23_2Request["payload"]["cadence"]
  readonly next?: Endpoint23_2Request["payload"]["next"]
  readonly timezone?: Endpoint23_2Request["payload"]["timezone"]
  readonly enabled?: Endpoint23_2Request["payload"]["enabled"]
}
const Endpoint23_2 = (raw: RawClient["server.schedule"]) => (input: Endpoint23_2Input) =>
  raw["schedule.update"]({
    params: { scheduleID: input["scheduleID"] },
    query: { location: input["location"] },
    payload: {
      name: input["name"],
      prompt: input["prompt"],
      cadence: input["cadence"],
      next: input["next"],
      timezone: input["timezone"],
      enabled: input["enabled"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint23_3Request = Parameters<RawClient["server.schedule"]["schedule.remove"]>[0]
type Endpoint23_3Input = {
  readonly scheduleID: Endpoint23_3Request["params"]["scheduleID"]
  readonly location?: Endpoint23_3Request["query"]["location"]
}
const Endpoint23_3 = (raw: RawClient["server.schedule"]) => (input: Endpoint23_3Input) =>
  raw["schedule.remove"]({ params: { scheduleID: input["scheduleID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint23_4Request = Parameters<RawClient["server.schedule"]["schedule.run"]>[0]
type Endpoint23_4Input = {
  readonly scheduleID: Endpoint23_4Request["params"]["scheduleID"]
  readonly location?: Endpoint23_4Request["query"]["location"]
}
const Endpoint23_4 = (raw: RawClient["server.schedule"]) => (input: Endpoint23_4Input) =>
  raw["schedule.run"]({ params: { scheduleID: input["scheduleID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup23 = (raw: RawClient["server.schedule"]) => ({
  list: Endpoint23_0(raw),
  create: Endpoint23_1(raw),
  update: Endpoint23_2(raw),
  remove: Endpoint23_3(raw),
  run: Endpoint23_4(raw),
})

type Endpoint24_0Request = Parameters<RawClient["server.capability.operator"]["capability.operator.inspect"]>[0]
type Endpoint24_0Input = { readonly location?: Endpoint24_0Request["query"]["location"] }
const Endpoint24_0 = (raw: RawClient["server.capability.operator"]) => (input?: Endpoint24_0Input) =>
  raw["capability.operator.inspect"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup24 = (raw: RawClient["server.capability.operator"]) => ({ inspect: Endpoint24_0(raw) })

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  location: adaptGroup1(raw["server.location"]),
  agents: adaptGroup2(raw["server.agent"]),
  sessions: adaptGroup3(raw["server.session"]),
  messages: adaptGroup4(raw["server.message"]),
  models: adaptGroup5(raw["server.model"]),
  providers: adaptGroup6(raw["server.provider"]),
  integrations: adaptGroup7(raw["server.integration"]),
  credentials: adaptGroup8(raw["server.credential"]),
  permissions: adaptGroup9(raw["server.permission"]),
  files: adaptGroup10(raw["server.fs"]),
  commands: adaptGroup11(raw["server.command"]),
  skills: adaptGroup12(raw["server.skill"]),
  behaviors: adaptGroup13(raw["server.behavior"]),
  events: adaptGroup14(raw["server.event"]),
  ptys: adaptGroup15(raw["server.pty"]),
  questions: adaptGroup16(raw["server.question"]),
  references: adaptGroup17(raw["server.reference"]),
  projectCopies: adaptGroup18(raw["server.projectCopy"]),
  relayDocuments: adaptGroup19(raw["server.relay.document"]),
  relayPublish: adaptGroup20(raw["server.relay.publish"]),
  relayHooks: adaptGroup21(raw["server.relay.hook"]),
  pullRequests: adaptGroup22(raw["server.pullRequest"]),
  schedules: adaptGroup23(raw["server.schedule"]),
  operator: adaptGroup24(raw["server.capability.operator"]),
})

export const make = (options?: {
  readonly baseUrl?: URL | string
  readonly headers?: Readonly<Record<string, string>>
}) => {
  if (options?.headers === undefined) return HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
  // Snapshot and validate host configuration now, before this Effect can be executed or reused.
  const headers = snapshotHeaders(options.headers)
  if (Object.keys(headers).length === 0) return HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
  // Fetch must supply the multipart boundary; only explicit request headers may override it.
  const formHeaders = Object.fromEntries(Object.entries(headers).filter(([name]) => name !== "content-type"))
  return HttpApiClient.make(ClientApi, {
    baseUrl: options.baseUrl,
    transformClient: (client) =>
      HttpClient.mapRequest(client, (request) =>
        HttpClientRequest.setHeaders(request, {
          ...(request.body._tag === "FormData" ? formHeaders : headers),
          ...request.headers,
        }),
      ),
  }).pipe(Effect.map(adaptClient))
}

function snapshotHeaders(input: Readonly<Record<string, string>>) {
  if (
    typeof input !== "object" ||
    input === null ||
    (Object.getPrototypeOf(input) !== Object.prototype && Object.getPrototypeOf(input) !== null)
  ) {
    throw new TypeError("Invalid client headers")
  }
  const entries = Object.entries(Object.getOwnPropertyDescriptors(input)).flatMap(([name, descriptor]) => {
    if (
      !/^[!#$%&'*+.^_|~0-9A-Za-z\x60-]+$/.test(name) ||
      !("value" in descriptor) ||
      typeof descriptor.value !== "string" ||
      /[\r\n]/.test(descriptor.value)
    ) {
      throw new TypeError("Invalid client headers")
    }
    return descriptor.enumerable ? [[name, descriptor.value] as const] : []
  })
  try {
    return Object.freeze(Object.fromEntries(new Headers(Object.fromEntries(entries))))
  } catch (error) {
    if (error instanceof TypeError) throw new TypeError("Invalid client headers")
    throw error
  }
}
