import {
  createSourceFile,
  forEachChild,
  isIdentifier,
  isTypeAliasDeclaration,
  isTypeQueryNode,
  isTypeReferenceNode,
  ScriptKind,
  ScriptTarget,
  SyntaxKind,
  type Node,
} from "typescript"

// Partition exported non-generic aliases without reprinting their bytes. Referenced names must be exported aliases
// in the original generated module; unsupported references fail instead of inventing imports or losing type safety.
export function splitTypes(source: string, names: readonly string[]) {
  if (names.length === 0) throw new Error("SdkTypePartition: empty-selection")
  if (new Set(names).size !== names.length) throw new Error("SdkTypePartition: duplicate-selection")
  const parsed = createSourceFile("types.gen.ts", source, ScriptTarget.Latest, true, ScriptKind.TS)
  const aliases = parsed.statements.filter(isTypeAliasDeclaration)
  const selected = names.map((name) => {
    const matches = aliases.filter((node) => node.name.text === name)
    if (matches.length === 0) throw new Error(`SdkTypePartition: missing-type ${name}`)
    if (matches.length !== 1) throw new Error(`SdkTypePartition: duplicate-type ${name}`)
    const node = matches[0]
    if (!node.modifiers?.some((item) => item.kind === SyntaxKind.ExportKeyword))
      throw new Error(`SdkTypePartition: not-exported ${name}`)
    if (node.typeParameters?.length) throw new Error(`SdkTypePartition: unsupported-generic ${name}`)
    return node
  })
  const references = new Set<string>()
  selected.forEach((alias) => {
    const visit = (node: Node): void => {
      if (isTypeQueryNode(node)) throw new Error(`SdkTypePartition: unsupported-type-query ${alias.name.text}`)
      if (isTypeReferenceNode(node)) {
        if (!isIdentifier(node.typeName)) throw new Error(`SdkTypePartition: qualified-reference ${alias.name.text}`)
        references.add(node.typeName.text)
      }
      forEachChild(node, visit)
    }
    visit(alias.type)
  })
  const dependencies = [...references].filter((name) => !names.includes(name)).toSorted()
  dependencies.forEach((name) => {
    const matches = aliases.filter((node) => node.name.text === name)
    if (matches.length !== 1 || !matches[0].modifiers?.some((item) => item.kind === SyntaxKind.ExportKeyword))
      throw new Error(`SdkTypePartition: missing-or-ambiguous-dependency ${name}`)
  })
  const remaining = selected
    .toSorted((left, right) => left.pos - right.pos)
    .reduce(
      (state, node) => ({
        text: state.text + source.slice(state.end, node.getFullStart()),
        end: node.end,
      }),
      { text: "", end: 0 },
    )
  return {
    main: `import type { ${names.join(", ")} } from "./maestro-events.gen.js"\nexport type { ${names.join(", ")} } from "./maestro-events.gen.js"\n${remaining.text}${source.slice(remaining.end)}`,
    partition: `// Generated by script/build.ts from @hey-api/openapi-ts type declarations.\n${
      dependencies.length ? `import type { ${dependencies.join(", ")} } from "./types.gen.js"\n` : ""
    }${selected.map((node) => source.slice(node.getFullStart(), node.end)).join("\n")}\n`,
  }
}
