// Generated by @orchestra/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClient, HttpClientError, HttpClientRequest } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { Api } from "../default-headers.test"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof Api>

const mapClientError = <E,>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["probe"]) => () => raw["read"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint0_1Request = Parameters<RawClient["probe"]["override"]>[0]
type Endpoint0_1Input = {
  readonly aUtHoRiZaTiOn?: Endpoint0_1Request["headers"]["aUtHoRiZaTiOn"]
  readonly "X-Factory"?: Endpoint0_1Request["headers"]["X-Factory"]
  readonly "x-orchestra-location"?: Endpoint0_1Request["headers"]["x-orchestra-location"]
}
const Endpoint0_1 = (raw: RawClient["probe"]) => (input?: Endpoint0_1Input) =>
  raw["override"]({
    headers: {
      aUtHoRiZaTiOn: input?.["aUtHoRiZaTiOn"],
      "X-Factory": input?.["X-Factory"],
      "x-orchestra-location": input?.["x-orchestra-location"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint0_2Request = Parameters<RawClient["probe"]["json"]>[0]
type Endpoint0_2Input = { readonly message: Endpoint0_2Request["payload"]["message"] }
const Endpoint0_2 = (raw: RawClient["probe"]) => (input: Endpoint0_2Input) =>
  raw["json"]({ payload: { message: input["message"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint0_3Request = Parameters<RawClient["probe"]["upload"]>[0]
type Endpoint0_3Input = { readonly message: Endpoint0_3Request["payload"]["message"] }
const Endpoint0_3 = (raw: RawClient["probe"]) => (input: Endpoint0_3Input) =>
  raw["upload"]({ payload: { message: input["message"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint0_4Request = Parameters<RawClient["probe"]["events"]>[0]
type Endpoint0_4Input = { readonly authorization?: Endpoint0_4Request["headers"]["authorization"] }
const Endpoint0_4 = (raw: RawClient["probe"]) => (input?: Endpoint0_4Input) =>
  Stream.unwrap(
    raw["events"]({ headers: { authorization: input?.["authorization"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup0 = (raw: RawClient["probe"]) => ({
  read: Endpoint0_0(raw),
  override: Endpoint0_1(raw),
  json: Endpoint0_2(raw),
  upload: Endpoint0_3(raw),
  events: Endpoint0_4(raw),
})

const adaptClient = (raw: RawClient) => ({ probe: adaptGroup0(raw["probe"]) })

export const make = (options?: {
  readonly baseUrl?: URL | string
  readonly headers?: Readonly<Record<string, string>>
}) => {
  if (options?.headers === undefined) return HttpApiClient.make(Api, options).pipe(Effect.map(adaptClient))
  // Snapshot and validate host configuration now, before this Effect can be executed or reused.
  const headers = snapshotHeaders(options.headers)
  if (Object.keys(headers).length === 0) return HttpApiClient.make(Api, options).pipe(Effect.map(adaptClient))
  // Fetch must supply the multipart boundary; only explicit request headers may override it.
  const formHeaders = Object.fromEntries(Object.entries(headers).filter(([name]) => name !== "content-type"))
  return HttpApiClient.make(Api, {
    baseUrl: options.baseUrl,
    transformClient: (client) =>
      HttpClient.mapRequest(client, (request) =>
        HttpClientRequest.setHeaders(request, {
          ...(request.body._tag === "FormData" ? formHeaders : headers),
          ...request.headers,
        }),
      ),
  }).pipe(Effect.map(adaptClient))
}

function snapshotHeaders(input: Readonly<Record<string, string>>) {
  if (
    typeof input !== "object" ||
    input === null ||
    (Object.getPrototypeOf(input) !== Object.prototype && Object.getPrototypeOf(input) !== null)
  ) {
    throw new TypeError("Invalid client headers")
  }
  const entries = Object.entries(Object.getOwnPropertyDescriptors(input)).flatMap(([name, descriptor]) => {
    if (
      !/^[!#$%&'*+.^_|~0-9A-Za-z\x60-]+$/.test(name) ||
      !("value" in descriptor) ||
      typeof descriptor.value !== "string" ||
      /[\r\n]/.test(descriptor.value)
    ) {
      throw new TypeError("Invalid client headers")
    }
    return descriptor.enumerable ? [[name, descriptor.value] as const] : []
  })
  try {
    return Object.freeze(Object.fromEntries(new Headers(Object.fromEntries(entries))))
  } catch (error) {
    if (error instanceof TypeError) throw new TypeError("Invalid client headers")
    throw error
  }
}
