// Source-to-target audit register, TechLead a68e7af92c7ed5aaf8b6574b7ad2f705fb38eeb5.
// Copyright 2026 HuGR Labs. Apache-2.0 (http://www.apache.org/licenses/LICENSE-2.0).
// Adaptation: native TypeScript, host authority/evidence, bounded state, selective recovery.
export const GOVERNANCE_SOURCE = "a68e7af92c7ed5aaf8b6574b7ad2f705fb38eeb5"
export const GOVERNANCE_CAPABILITIES = [
  { source: "release.sh", target: "src/governance/repository.ts", operatorTarget: "src/governance/operators.ts", capabilities: ["release-propose", "release-run"], tests: "test/native-seams.governance.test.ts", host: ["committed-repository-release-recipe", "explicit-native-tag-publish-intent", "actual-context-authorization"] },
  { source: ".githooks/commit-msg", target: "src/governance/repository.ts", capabilities: ["commitlint"], tests: "test/repository.governance.test.ts", host: ["actual-Git-message-acquisition", "native-commit-boundary-binding"] },
  { source: "governance/GOVERNANCE.md", target: "src/governance/HOST-BINDINGS.md", capabilities: ["audit", "usage", "policy-propose"], tests: "test/evidence.governance.test.ts", host: ["native-Session-events-and-permissions"] },
  { source: "governance/_state.py", target: "src/governance/state.ts", capabilities: ["bounded-read", "atomic-project-state", "canonical-IDs"], tests: "test/state.governance.test.ts", host: ["project-state-directory", "native-read-write-permission"] },
  { source: "governance/acceptance-gate.py", target: "src/governance/acceptance.ts", capabilities: ["acceptance"], tests: "test/evidence.governance.test.ts", host: ["actual-check-captures", "source-pre-green-contract"] },
  { source: "governance/audit-trail.py", target: "src/governance/telemetry.ts", capabilities: ["audit"], tests: "test/evidence.governance.test.ts", host: ["Session-event-observations", "local-native-EventV2-seal-window"], hostTargets: ["packages/core/src/event.ts", "packages/core/src/event/seal.ts", "packages/orchestra/src/maestro/arsenal-observations.ts", "packages/core/src/tool/maestro-arsenal.ts"], hostTests: ["packages/orchestra/test/maestro/arsenal-integrity.test.ts", "packages/orchestra/test/maestro/arsenal-integrity-report.test.ts"], adaptation: "retained-event-window-only-not-full-history-or-observation-verification" },
  { source: "governance/change-budget.py", target: "src/governance/repository.ts", capabilities: ["change-budget"], tests: "test/repository.governance.test.ts", host: ["Git-process-permission", "explicit-budget-and-exclusions"] },
  { source: "governance/changelog-bump.py", target: "src/governance/repository.ts", operatorTarget: "src/governance/operators.ts", capabilities: ["changelog-propose", "changelog-write"], tests: "test/native-seams.governance.test.ts", host: ["actual-native-edit-authorization", "operator-curation"] },
  { source: "governance/changelog-check.py", target: "src/governance/repository.ts", capabilities: ["changelog-check"], tests: "test/repository.governance.test.ts", host: ["actual-package-and-changelog-paths"] },
  { source: "governance/ci-select.py", target: "src/governance/repository.ts", capabilities: ["ci-select"], tests: "test/repository.governance.test.ts", host: ["actual-CI-group-rules", "universal-check-names", "actual-check-execution"] },
  { source: "governance/cost-governor.py", target: "src/governance/telemetry.ts", boundaryTarget: "src/tools/governance.ts", capabilities: ["cost-estimate"], tests: "test/cost-estimate.governance.test.ts", host: ["explicit-provider-pricing", "explicit-budget", "estimate-boundary-isError-refusal"], adaptation: "raw-finite-USD-comparison-stricter-than-source-four-decimal-rounding" },
  { source: "governance/github-ruleset.sh", target: "src/governance/repository.ts", operatorTarget: "src/governance/operators.ts", capabilities: ["ruleset-propose", "ruleset-run"], tests: "test/native-seams.governance.test.ts", host: ["explicit-native-operator-intent", "actual-native-process-permission", "actual-API-response"] },
  { source: "governance/loc-cap.sh", target: "src/governance/repository.ts", capabilities: ["loc-cap"], tests: "test/repository.governance.test.ts", host: ["explicit-source-path-coverage", "actual-file-read-permission"] },
  { source: "governance/mission-control.py", target: "src/governance/telemetry.ts", capabilities: ["status"], tests: "test/evidence.governance.test.ts", host: ["actual-Session-observations"] },
  { source: "governance/policy-enforce.py", target: "src/governance/policy.ts", capabilities: ["policy-propose"], tests: "test/repository.governance.test.ts", host: ["F-native-before-after-interception", "actual-permission-owner"] },
  { source: "governance/roi-telemetry.py", target: "src/governance/telemetry.ts", capabilities: ["usage"], tests: "test/evidence.governance.test.ts", host: ["provider-usage-Session-events", "explicit-provider-pricing"] },
  { source: "governance/sandbox-launch.py", target: "src/governance/policy.ts", capabilities: ["sandbox-propose"], tests: "test/repository.governance.test.ts", host: ["E-native-execution-endpoint", "F-actual-process-filesystem-confinement"] },
  { source: "governance/srt_policy.py", target: "src/governance/policy.ts", capabilities: ["policy-propose", "sandbox-propose"], tests: "test/repository.governance.test.ts", host: ["native-policy-binding", "actual-permissions", "profile-is-preference"] },
  { source: "governance/wave-metrics.py", target: "src/governance/repository.ts", capabilities: ["metrics-snapshot", "metrics-report", "usage"], tests: "test/repository.governance.test.ts", host: ["explicit-metric-scope", "actual-result-captures", "Session-usage-observations"] },
  { source: "governance/wave-preflight.py", target: "src/governance/preflight.ts", capabilities: ["preflight-arm", "preflight-check", "preflight-disarm"], tests: "test/repository.governance.test.ts", host: ["named-real-smokes", "actual-baseline-checks", "F-dispatch-binding"] },
  { source: "governance/wave-txn.py", target: "src/governance/recovery.ts", capabilities: ["recovery-begin", "recovery-prepare", "recovery-restore", "recovery-status", "recovery-replay"], tests: "test/recovery.governance.test.ts", host: ["explicit-owned-files", "native-edit-process-permission", "serialize-recovery-edits"] },
  { source: "mcp/src/onboard/profile.ts", target: "src/onboard/profile.ts", capabilities: ["profile"], tests: "test/profile.test.ts", host: ["actual-permission-owner"] },
  { source: "mcp/src/tools/profile.ts", target: "src/tools/profile.ts", capabilities: ["profile"], tests: "test/profile.test.ts", host: ["project-state-directory"] },
  { source: "mcp/src/tools/relay-arm.ts", target: "src/tools/relay-arm.ts", capabilities: ["relay-arm", "completion-check"], tests: "test/evidence.governance.test.ts", host: ["named-native-check-bindings", "actual-completion-captures", "F-lifecycle-enforcement"] },
  { source: "mcp/src/tools/wave-ledger.ts", target: "src/tools/wave-ledger.ts", capabilities: ["wave-ledger"], tests: "test/ledger.governance.test.ts", host: ["actual-WP-outcome-observations", "compaction-receipt-storage"] },
  { source: "mcp/src/tools/wave-scheduler.ts", target: "src/tools/wave-scheduler.ts", capabilities: ["wave-scheduler"], tests: "test/scheduler.test.ts", host: ["actual-ordered-wave-events", "verification-and-review-seal"] },
  { source: "mcp/src/engine/scheduler.ts", target: "src/engine/scheduler.ts", capabilities: ["wave-scheduler"], tests: "test/scheduler.test.ts", host: ["actual-dispatch-merge-execution"] },
  { source: "mcp/src/engine/scheduler-fold.ts", target: "src/engine/scheduler-fold.ts", capabilities: ["wave-scheduler"], tests: "test/scheduler.test.ts", host: ["ordered-observed-event-replay"] },
] as const
export const GOVERNANCE_TEST_TRACE = [
  ["test-state.py", "test/state.governance.test.ts"],
  ["test-acceptance-gate.py", "test/evidence.governance.test.ts"],
  ["test-change-budget.py", "test/repository.governance.test.ts"],
  ["test-ci-select.py", "test/repository.governance.test.ts"],
  ["test-commitlint.py", "test/repository.governance.test.ts"],
  ["test-cost-governor.py", "test/cost-estimate.governance.test.ts"],
  ["test-governance.py", "test/evidence.governance.test.ts"],
  ["test-mission-control.py", "test/evidence.governance.test.ts"],
  ["test-policy-enforce.py", "test/repository.governance.test.ts"],
  ["test-preflight.py", "test/repository.governance.test.ts"],
  ["test-sandbox-live.sh", "test/repository.governance.test.ts"],
  ["test-srt-policy.py", "test/repository.governance.test.ts"],
  ["test-wave-metrics.py", "test/repository.governance.test.ts"],
  ["test-wave-txn.py", "test/recovery.governance.test.ts"],
] as const
